Feature: Lending stream FAQs contact-us page test plan

  @LS @MobileView @UI @Faqs @Contact-Us @Body @content
  Scenario Outline: LS: FAQs: contact-us : Verify the Contact Us FAQ page body contents
    Given I want to launch the url "https://www.lendingstream.co.uk/faqs/contact-us/"
    Then I verify the url "https://www.lendingstream.co.uk/faqs/contact-us/"
    Then I verify <content> is present
    Examples:
      | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | How can I contact you if I have a problem?                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | You can contact us:                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | on our Contact Us page                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | by phone on 0203 808 4440#. Our call centre representatives are available 8 AM to 8 PM, 7 days a week to assist you.                                                                                                                                                                                                                                                                                                                                                       |
      | If you'd like to file a complaint, you can find information about how to do that here.                                                                                                                                                                                                                                                                                                                                                                                     |
      | If you are having difficulty repaying on time, please contact us immediately. We want to help. We will work with you to arrange an affordable alternative payment plan.                                                                                                                                                                                                                                                                                                    |
      | If you don't let us know that you are having financial difficulties, we will continue collecting your next payment automatically. That could empty your account of money you need for essential living expenses and send your account into arrears, resulting in a late fee.                                                                                                                                                                                               |
      | If you're having financial difficulty, the Financial Conduct Authority has a list of recommended places to get advice.                                                                                                                                                                                                                                                                                                                                                     |
      | Money Advice Service                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | For free, unbiased and easy-to-access money tools, information and advice, visit www.moneyadviceservice.org.uk or phone 0300 500 5000 to speak to a Money Adviser.                                                                                                                                                                                                                                                                                                         |
      | Money Advice Scotland                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | If you live in Scotland, phone 0141 572 0237 or visit www.moneyadvicescotland.org.uk to find contact details for debt advice in your local area.                                                                                                                                                                                                                                                                                                                           |
      | Advice NI - Debt Action NI service                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | If you live in Northern Ireland, phone 0800 917 4607, email debt@adviceni.net or visit www.debtaction-ni.net for debt advice.                                                                                                                                                                                                                                                                                                                                              |
      | AdviceUK                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | Member centres offer debt advice including specialist advice for minority communities and people with disabilities - visit www.adviceuk.org.uk or phone 0300 777 0107.                                                                                                                                                                                                                                                                                                     |
      | Christians Against Poverty (CAP)                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | For free debt advice in your home, check post code coverage at www.capuk.org then call 0800 328 0006.                                                                                                                                                                                                                                                                                                                                                                      |
      | Citizens Advice                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | For advice and information on debt and other topics, visit your local Citizens Advice Bureau (address in the phone book) or go to www.adviceguide.org.uk.                                                                                                                                                                                                                                                                                                                  |
      | National Debtline                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | If you live in England, Wales or Scotland phone 0808 808 4000 or visit www.nationaldebtline.org for debt advice and information.                                                                                                                                                                                                                                                                                                                                           |
      | StepChange Debt Charity                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | For debt advice throughout the UK phone 0800 138 1111 or visit www.stepchange.org.                                                                                                                                                                                                                                                                                                                                                                                         |
      | Learn more about the cost of your loan, default charges, risks and prepayments.                                                                                                                                                                                                                                                                                                                                                                                            |
      | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status checks, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability. |
      | We don’t offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721.0%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed) you would owe 6 equal repayments of 64.44. You will repay 386.61 in total, there are no additional fees.                                                                                                                      |

  @LS @Desktop @MobileView @UI @Faqs @Contact-Us @Body @content
  Scenario: LS: FAQs: contact-us : Verify the Rep APR in Contact Us FAQ page with purple Background
    Given I want to launch the url "https://www.lendingstream.co.uk/faqs/contact-us/"
    Then I verify the url "https://www.lendingstream.co.uk/faqs/contact-us/"
    Then I verify "Representative 1333% APR" is present in purple Background

  @LS @Desktop @MobileView @UI @Faqs @Contact-Us @Body @link
  Scenario Outline: LS: FAQs: contact-us : Verify all the links in Contact Us FAQ page
    Given I want to launch the url "https://www.lendingstream.co.uk/faqs/contact-us/"
    Then I verify the url "https://www.lendingstream.co.uk/faqs/contact-us/"
    Then I verify <link> is present
    Then I click on the <link> link
    Then I verify the <url>
    Examples:
      | link                          | url                                                          |
      | Home                          | https://www.lendingstream.co.uk                              |
      | FAQs                          | https://www.lendingstream.co.uk/faqs/                        |
      | Contact us                    | https://www.lendingstream.co.uk/contactus/                   |
      | here                          | https://www.lendingstream.co.uk/faqs/complaints/             |
      | please contact us immediately | https://www.lendingstream.co.uk/contactus/                   |
      | Back to FAQs                  | https://www.lendingstream.co.uk/faqs/                        |
      | cost of your loan             | https://www.lendingstream.co.uk/faqs/representative-example/ |
      | default charges               | https://www.lendingstream.co.uk/faqs/loan-fees/              |
      | risks and prepayments.        | https://www.lendingstream.co.uk/faqs/loan-risks/             |
