Feature: Lending stream Loans same day loans page test plan

  @LS @Desktop @MobileView @UI @Loans_Page @same-day-loans @Body @content
  Scenario Outline: LS: loans : Verify the body content in same-day-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/same-day-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/same-day-loans/"
    Then I verify <content> is present
    Examples:
      | content                                                                                                                                                                                                                                                                                                                                                                                                             |
      | Same Day Loans                                                                                                                                                                                                                                                                                                                                                                                                      |
      | What are same day loans?                                                                                                                                                                                                                                                                                                                                                                                            |
      | Same day loans give you the funds the same day you apply. If you're approved, same day loans are a way of getting cash in your account quickly, so you can use it as fast as possible. They're usually used to help with short-term financial emergencies (broken washing machines, cars breaking down… that sort of thing).                                                                                       |
      | If you search for same day loans, most of the ones you'll see are 'payday loans'. This is usually a way to describe short-term loans?. While most of them are usually for repayment around one month, they can range over other, relatively short periods, depending on the lender. But some longer-term loans (such as Lending Stream six month loans) are also same day loans, while offering more time to repay. |
      | Are Lending Stream loans same day loans?                                                                                                                                                                                                                                                                                                                                                                            |
      | Yes, they are. In fact, most of the time, Lending Stream loans could be a better solution than same day loans.                                                                                                                                                                                                                                                                                                      |
      | Lending Stream aim to provide you with your funds the same day no matter what time you apply. Some of our competitors only process loans during office hours, or don't do them after a certain time at night. In some situations, you can apply and not get cash until the following day. We'll send the cash to your bank in under 90 seconds if your loan is agreed.                                              |
      | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                            |
      | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                       |
      | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                          |
      | Cash sent to your bank in under 90 seconds. Depending on your bank, it may take longer to reach your account.                                                                                                                                                                                                                                                                                                       |
      | How to get same day loans                                                                                                                                                                                                                                                                                                                                                                                           |
      | Applying for same day loans is usually straightforward. In most cases, you apply online, get a decision and then the cash is transferred if you're approved. You set up the repayments as part of the application process.                                                                                                                                                                                          |
      | With Lending Stream same day loans, you apply online and you'll get an instant decision. If your loan is agreed, we'll send the cash to your bank in under 90 seconds.                                                                                                                                                                                                                                              |
      | How much can you borrow for a same day loan?                                                                                                                                                                                                                                                                                                                                                                        |
      | If you apply via Lending Stream, you can apply for any amount from £50 to £800 if you're a new customer. If you're a returning customer and you've shown that you're good at repaying, you can apply for up to £1500.                                                                                                                                                                                               |
      | Are same day loans safe?                                                                                                                                                                                                                                                                                                                                                                                            |
      | Same day loans are generally safe, as long as you're careful when you apply.                                                                                                                                                                                                                                                                                                                                        |
      | You should make sure that you're applying with a lender who is regulated by the Financial Conduct Authority (FCA). This means that the lender is accountable and you can raise issues with the FCA to get them resolved. If the lender isn't authorised, this could mean you aren't treated fairly or that the lender isn't conducting business properly.                                                           |
      | You can check if a lender is authorised by looking for their registration number. Most lenders have it on the footer on their website, but it may be on their 'about us' page. You can also check the FCA website, which has a lender registry, to see if the lender is on there.                                                                                                                                   |
      | It's also worth remembering that same day loans do turn up on your credit report. If you think you're going to struggle to repay the loan, then it could end up leaving a negative mark on your credit report, as well as costing more money through late fees and a longer lending period.                                                                                                                         |
      | If things end up changing for you financially and you suddenly can't make your repayments on time, contact your lender as soon as possible. You may be able to set up a repayment scheme that fits your new circumstances better. With Lending Stream, we'll help you set up a repayment plan if you're having difficulty repaying.                                                                                 |
      | Where to get same day loans                                                                                                                                                                                                                                                                                                                                                                                         |
      | If you want to apply for a same day loan, you can do it either online or in person. However, if you apply in a high-street lending store like The Money Shop, then the process might be slightly different to online. In most high-street lending stores, you'll apply with a person, who'll help you fill in the forms and set up repayment.                                                                       |
      | Most people apply with same day loan direct lenders online, as you can do it in your own time and without having to deal with a customer service representative (unless any details need to be checked).                                                                                                                                                                                                            |
      | Same day loans with no guarantor or credit checks                                                                                                                                                                                                                                                                                                                                                                   |
      | Same day loans generally don't need a guarantor, however if your credit record is poor, you may not be accepted. This is because same day loans that are for a short period of time tend to be more expensive if you don't repay them on time.                                                                                                                                                                      |
      | Some guarantor loans may be same day loans, however, the process involves more activity from you, as you have to find a guarantor.                                                                                                                                                                                                                                                                                  |
      | Same day loans generally involve credit checks – alternatively if you're pawning something to fund borrowing, it may not involve a credit check, though. But for most online loans, you can realistically expect a credit check to be part of the application.                                                                                                                                                     |
      | Do same day loans affect your credit rating?                                                                                                                                                                                                                                                                                                                                                                        |
      | Yes, they do. This doesn't have to be bad news – if you repay on time, a same day loan will be recorded on your credit record as a repaid loan, which can actually help how your credit record is perceived by other lenders.                                                                                                                                                                                      |
      | If you don't repay on time, missed payments could be recorded. If you default on the loan, this is likely to reflect poorly on your credit history.                                                                                                                                                                                                                                                                 |
      | What if I can't pay back a same day loan?                                                                                                                                                                                                                                                                                                                                                                           |
      | If you take out a same day loan and then have financial difficulties, you may not be able to make the repayments as originally planned. In this situation, it's always sensible to contact the lender, as they may be able to arrange alternative methods of repayments.                                                                                                                                            |
      | With Lending Stream same day loans, we'll help you set up a repayment plan if you're having financial difficulty. This will be with the aim of helping you repay the loan, but in a way that works best with your current financial situation.                                                                                                                                                                      |
      | If you don't contact us, it may mean that you receive a late payment fee, or even that your account could get passed to a debt collection agency. It could also affect your credit history and rating. Setting up a repayment plan is straightforward, so it won't take you long to do.                                                                                                                             |


  @LS @Desktop @MobileView @UI @Loans_Page @same-day-loans @Body @link
  Scenario Outline: LS: loans : Check all the links in same-day-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/same-day-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/same-day-loans/"
    Then I verify <link> is present.
    Then I click on the <link> link
    Then I verify the <url>
    Examples:
      | link                      | url                                                                     |
      | Home                      | https://www.lendingstream.co.uk                                         |
      | Loans                     | https://www.lendingstream.co.uk/loans/                                  |
      | payday Loans              | https://www.lendingstream.co.uk/loans/payday-loans/                     |
      | short-term loans?         | https://www.lendingstream.co.uk/loans/short-term-loans/                 |
      | Apply Now                 | https://www.lendingstream.co.uk/application/apply/                      |
      | moneyadviceservice.org.uk | https://www.moneyadviceservice.org.uk/en                                |
      | about us                  | https://www.lendingstream.co.uk/about-us/                               |
      | Bad Credit Loans          | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 |
      | Payday Loans              | https://www.lendingstream.co.uk/loans/payday-loans/                     |
      | Short-Term Loans          | https://www.lendingstream.co.uk/loans/short-term-loans/                 |
      | Compare Loans             | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ |
      | Quick Loans               | https://www.lendingstream.co.uk/loans/quick-loans/                      |
      | Unsecured Loans           | https://www.lendingstream.co.uk/loans/unsecured-loans/                  |