Feature: Lending stream Loans Bad credit loans page test plan

  @LS @Desktop @MobileView @UI @Loans_Page @bad-credit-loans @Body @content
  Scenario Outline: LS: loans : Verify the body content in bad-credit-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify <content> is present
    Examples:
      | content                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | Bad Credit Loans                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | What you need to know about Bad Credit Loans                                                                                                                                                                                                                                                                                                                                                                                      |
      | Are bad credit loans a real thing?                                                                                                                                                                                                                                                                                                                                                                                                |
      | There isn't a specific financial product called 'a bad credit loan'. It's a term that usually refers to payday loans or similar short-term loans that might accept people who don't have a good credit history.                                                                                                                                                                                                                   |
      | There are certainly plenty of lenders who are willing to offer payday loans to people with poor credit, but it's important to make sure you're shopping around – payday loans and short-term loans can sometimes be very expensive.                                                                                                                                                                                              |
      | Do Lending Stream offer bad credit loans?                                                                                                                                                                                                                                                                                                                                                                                         |
      | We understand that you can have bad credit for a number of reasons, and it doesn't necessarily mean that you're irresponsible with your finances. We'll take your credit score into account as part of a personalised review, but we'll also look at your current circumstances and your ability to repay.                                                                                                                        |
      | If we believe you can't repay, we won't lend to you. But if we offer you a loan, it'll be because we believe you can repay, based on our checks and the information that you provide. Even if you have bad credit.                                                                                                                                                                                                                |
      | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                          |
      | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                     |
      | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                        |
      | Can I apply for a loan with bad credit?                                                                                                                                                                                                                                                                                                                                                                                           |
      | You can apply for a loan with bad credit, but you may not qualify for the lower rates of interest that are available to people with better credit. Basically, having a good or bad credit rating is a measure of how good you've been at repaying credit. Having poor credit suggests you're a higher risk, so the price of the loan reflects that.                                                                               |
      | While your credit rating is almost always a factor in a lending decision, there are other factors that 'bad credit lenders' consider as well. This is particularly the case when it comes to relatively small loans, as there's less risk involved than with a credit card or a mortgage.                                                                                                                                         |
      | Also, lenders concentrating on smaller amounts may be less concerned with a poor credit rating. As long as you can show that you can afford the loan repayments after taking into account your income and outgoings, then they may still lend to you.                                                                                                                                                                             |
      | The way lenders make money is based on people repaying them with interest. If lots of people don't repay them, they lose money. Lending to people with bad credit involves a higher interest rate, partly so it keeps working for the lender financially, even if some don't repay.                                                                                                                                               |
      | Payday loans for bad credit                                                                                                                                                                                                                                                                                                                                                                                                       |
      | The term 'bad credit loans' tends to be associated with payday loans. This is because high-cost short-term credit is often perceived as being something of a last resort. While this is true for some borrowers looking for online loans for bad credit, there are all kinds of reasons people take out payday loans, including a desire to avoid getting into longer-term debt.                                                  |
      | Because a payday loan is the most well-known type of loan that sometimes accepts people with a bad credit history, they're often seen as the same thing.                                                                                                                                                                                                                                                                          |
      | Why do so many places seem to offer bad credit loans?                                                                                                                                                                                                                                                                                                                                                                             |
      | There are lots of direct lenders offering bad credit loans because it can be profitable. That's what the whole credit industry is based on, from mortgages through credit cards and including more high-cost short-term credit.                                                                                                                                                                                                   |
      | Lenders are aware that some people can have poor credit but still be able to take on a relatively small short-term debt. So this is a potentially large customer base who have needs that more mainstream lenders aren't meeting.                                                                                                                                                                                                 |
      | How can I find out my credit rating?                                                                                                                                                                                                                                                                                                                                                                                              |
      | Finding out your credit rating has never been easier. There are three credit reference agencies in the UK – CallCredit, Experian and Equifax. You can view your credit report either through them or through sites like Clearscore or Noddle, who show you your information in a user-friendly way.                                                                                                                              |
      | One thing, just in case you're worried – viewing your credit score isn't the same thing as a credit search. When you apply for credit, the potential lender can search your credit file to make their decision. This can (slightly) reduce your credit score, especially if you apply for credit multiple times in a short time period. But you can view your own credit record as often as you want without causing any issues. |
      | Credit reference agencies keep track of your credit history, including the amount of credit you have and how you're doing on repayments. They also show where and who your financial history is linked to, which is useful if there are any possibilities of identity theft. When lenders search your credit file, they don't just see the 'score' you're given – they see your credit file and data for the last several years. |
      | They also show bad debts that have been reported to credit agencies – for example, unpaid utility bills. These can cause major problems on your credit score, so if they turn out to be mistakes or relatively easily resolved, this is worth knowing about. With bad debts like these, you may be able to resolve them and request them to remove the bad credit mark.                                                          |
      | What problems can bad credit cause me?                                                                                                                                                                                                                                                                                                                                                                                            |
      | Bad credit can cause you problems if you need to borrow in future. This may not be an issue immediately, but it could be a problem if you look for a mortgage, overdraft, credit card, etc.                                                                                                                                                                                                                                       |
      | It also could lead to the amount of credit available to you being reduced. In a situation like this, your credit card balance or overdraft limit could be reduced.                                                                                                                                                                                                                                                                |
      | How can I improve my credit rating?                                                                                                                                                                                                                                                                                                                                                                                               |
      | While this does not constitute financial advice, there are some straightforward steps (and some less straightforward ones) that may be able to help you improve your credit rating.                                                                                                                                                                                                                                               |
      | 1. Pay back whatever debt you can afford. One of the main things your credit score shows is how much of your available credit you're using. If you can lower that, that will almost certainly help your rating improve.                                                                                                                                                                                                           |
      | 2. Check for mistakes and outdated information. Are you still shown as living at an old address? Are you still financially linked to an ex-partner? There may be issues with your credit report that you know nothing about until you look – and some of them could be easily resolved.                                                                                                                                          |
      | 3. Make sure you repay on due dates. Using less credit will be useful, but if you constantly repay late, this will be a problem as well.                                                                                                                                                                                                                                                                                          |
      | If these three issues are all currently negatives on your credit report, then these will be useful first steps. However, there are more steps you can take if necessary. For help, go to moneyadviceservice.org.uk                                                                                                                                                                                                                |
      | Related Loans                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | We don’t offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721.0%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed) you would owe 6 equal repayments of 64.44. You will repay 386.61 in total, there are no additional fees.                                                                             |

  @LS @Desktop @MobileView @UI @Loans_Page @bad-credit-loans @Body @content @table
  Scenario Outline: LS: loans : Verify the table data in bad-credit-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify "Representative example" is present.
    Then I verify the <left_value> and <right_value> of the representative table.
    Examples:
      | left_value             | right_value |
      | Annual Interest Rate   | 292.0%      |
      | Total amount of credit | £200        |
      | Representative APR     | 1333%       |
      | Duration of agreement  | 6 months    |
      | Total amount payable   | £386.61     |
      | Total charge of credit | £186.61     |
      | Six repayments of:     | £64.44      |

  @LS @Desktop @MobileView @UI @Loans_Page @bad-credit-loans @Body @link
  Scenario Outline: LS: loans : Check all the links in bad-credit-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify "Related Loans" is present
    Then I verify <link> is present.
    Then I click on the <link> link
    Then I verify the <url>
    Examples:
      | link                      | url                                                                     |
      | Home                      | https://www.lendingstream.co.uk                                         |
      | Loans                     | https://www.lendingstream.co.uk/loans/                                  |
      | short-term loans          | https://www.lendingstream.co.uk/loans/short-term-loans/                 |
      | Apply Now                 | https://www.lendingstream.co.uk/application/apply/                      |
      | moneyadviceservice.org.uk | https://www.moneyadviceservice.org.uk/en                                |
      | payday loans              | https://www.lendingstream.co.uk/loans/payday-loans/                     |
      | Short-Term Loans          | https://www.lendingstream.co.uk/loans/short-term-loans/                 |
      | Payday Loans              | https://www.lendingstream.co.uk/loans/payday-loans/                     |
      | Unsecured Loans           | https://www.lendingstream.co.uk/loans/unsecured-loans/                  |
      | Compare Loans             | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ |
      | Quick Loans               | https://www.lendingstream.co.uk/loans/quick-loans/                      |
      | Same Day Loans            | https://www.lendingstream.co.uk/loans/same-day-loans/                   |

  @LS @Desktop @MobileView @UI @Loans_Page @bad-credit-loans @Body @link
  Scenario: LS: loans : Check the Money-advice-service link in bad-credit-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/bad-credit-loans/"
    Then I verify "moneyadviceservice.org.uk" link is present under "How can I improve my credit rating?".
    Then I click on the "moneyadviceservice.org.uk" link present under "How can I improve my credit rating?".
    Then I verify the url "https://www.moneyadviceservice.org.uk/en"