Feature: Lending stream Loans unsecured loans page test plan

  @LS @Desktop @MobileView @UI @Loans_Page @unsecured-loans @Body @content
  Scenario Outline: LS: loans : Verify the body content in unsecured-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/unsecured-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/unsecured-loans/"
    Then I verify <content> is present
    Examples:
      | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | Looking for unsecured loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | What are unsecured loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | Unsecured loans are loans where you don’t need any collateral. An unsecured loan isn’t taken out against anything. You just repay the loan plus interest (and some lenders might charge fees). Credit cards, overdrafts, payday loans and other short-term loans are all examples of unsecured loans. Six month loans from Lending Stream are another example of unsecured loans.                                                                                                             |
      | Secured loans, on the other hand, are based on something that the lender can take possession of if you fail to pay it back. So, mortgages or car loans are examples of a secured loan. On a smaller level, so are pawn shops. With secured loans, you could lose the possessions you use as collateral to borrow.                                                                                                                                                                               |
      | How do unsecured loans work?                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Because the loan is unsecured, a lender has to take other things into account – the most common being how likely you are to repay. This is part of the reason why so many lenders check your credit record.                                                                                                                                                                                                                                                                                    |
      | Depending on your credit record, an unsecured loan may well be more expensive than a secured one. This is often to help cover the risk the lender is taking.                                                                                                                                                                                                                                                                                                                                    |
      | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | How to apply for an unsecured loan                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | Unsecured loans can be applied for in most banks, post-offices and high-street credit stores (such as The Moneyshop, which provides loans like payday loans in the high-street as well as online). Almost all types of loans are available online as well, which can often be more convenient.                                                                                                                                                                                                  |
      | You’ll generally have to give your personal information and permission for your credit record to be checked. In some cases, you’ll also have to provide further paperwork (such as confirmation of ID, address and/or wages). If you’re applying with a bank or lender you’re already using, your current account behaviour may also inform the decision.                                                                                                                                   |
      | The amount of time it takes to get a decision in return varies between lenders. With Lending Stream you’ll get a quick decision, in most cases.                                                                                                                                                                                                                                                                                                                                                |
      | Can I get an unsecured loan without a guarantor?                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | A lot of the time, when people search for ‘unsecured loans no guarantor’ or ‘unsecured loans bad credit’, they’re looking for a short-term loan, but are struggling to find the right kind of loan for them.                                                                                                                                                                                                                                                                               |
      | This may be because a poor credit history causes problems for applicants, although it's usually not the only consideration for lenders. Some lenders will look at your current circumstances, especially when it's only for a short amount of time. However, there are no guarantees, and if lenders were to lend when they thought you couldn't repay, they wouldn't be lending responsibly.                                                                                                   |
      | Are unsecured loans risk-free?                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | If you try to take out a loan with an unlicensed lender, that could be very risky. If they’re not registered, then they’re not accountable, so you could be treated unfairly, or have difficulty complaining. You can check whether they’re licensed or not by looking for their consumer credit registration number or by searching the Financial Conduct Authority registration database for them (LINK).                                                                                  |
      | Also, any type of credit can be a risk, if you end up having difficulty repaying it. You should only ever take out credit that you know you can repay, although even then, things can go wrong. If you don’t repay, you may end up with negative marks on your credit report and your account may be passed onto a debt collection agency.                                                                                                                                                     |
      | Lending Stream tries to minimise these risks. We tell you up-front how much you’ll need to repay and when, and we allow you to make early repayments at no extra cost. If you’re late repaying, we won’t ever fine you more than £15 (in total, not per late payment). And if you have difficulty repaying, we’ll work with you to set up a repayment plan, so you can repay in a way that suits your immediate circumstances.                                                              |
      | How much do unsecured loans cost?                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | The cost of an unsecured loan depends on the lender the type of loan and the length of borrowing. An arranged overdraft may cost less than a credit card or a payday loan. And a loan from one bank may be considerably cheaper than a loan from another bank depending on your credit history.                                                                                                                                                                                                 |
      | Lenders are required to show the representative annual percentage rate for their loans when you apply. This shows the amount you’ll repay in total, including fees. It’s worth bearing in mind that representative APRs can be much higher for short-term loans, due in part to their short-time frame. This can happen because the percentages have to be compounded and multiplied to reach an annual figure, when most short term loans are for a considerably shorter period than a year. |
      | Things to remember about unsecured loans                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | There are a couple of important things to remember about unsecured loans                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | They’re unsecured, but they should still be paid on time. If you don’t, you may incur penalty charges and have to pay more interest than was originally planned due to the extra amount of time.                                                                                                                                                                                                                                                                                              |
      | They can affect your credit record – both positively and negatively. They’ll impact the total amount of credit you’re using, and your behaviour when repaying the loan will be reflected. If you repay it all on time, it’s usually a positive for your record, but it can be a negative if you don’t.                                                                                                                                                                                     |
      | The representative APR isn’t always what you’ll actually be offered. In some cases, it might be slightly lower or higher – the representative APR shows what at least 501% of successful applicants get offered.                                                                                                                                                                                                                                                                             |
      | We don’t offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721.0%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed) you would owe 6 equal repayments of 64.44. You will repay 386.61 in total, there are no additional fees.                                                                                                                                           |

  @LS @Desktop @MobileView @UI @Loans_Page @unsecured-loans @Body @link
  Scenario Outline: LS: loans : Check the links in unsecured-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/unsecured-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/unsecured-loans/"
    Then I verify <link> is present.
    Then I click on the <link> link
    Then I verify the <url>
    Examples:
      | link                       | url                                                                     |
      | Home                       | https://www.lendingstream.co.uk                                         |
      | Loans                      | https://www.lendingstream.co.uk/loans/                                  |
      | payday loans               | https://www.lendingstream.co.uk/loans/payday-loans/                     |
      | short-term loans           | https://www.lendingstream.co.uk/loans/short-term-loans/                 |
      | Apply Now                  | https://www.lendingstream.co.uk/application/apply/                      |
      | moneyadviceservice.org.uk. | https://www.moneyadviceservice.org.uk/en                                |
      | LINK                       | http://fca-consumer-credit-interim.force.com/CS_RegisterSearchPageNew   |
      | Find out more about APRs   | https://www.lendingstream.co.uk/apr-explained/                          |
      | Bad Credit Loans           | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 |
      | Payday Loans               | https://www.lendingstream.co.uk/loans/payday-loans/                     |
      | Short-Term Loans           | https://www.lendingstream.co.uk/loans/short-term-loans/                 |
      | Compare Loans              | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ |
      | Quick Loans                | https://www.lendingstream.co.uk/loans/quick-loans/                      |
      | Same Day Loans             | https://www.lendingstream.co.uk/loans/same-day-loans/                   |

  @LS @Desktop @MobileView @UI @Loans_Page @unsecured-loans @Body @link
  Scenario Outline: LS: loans : Check the payday and short-term loans link in same-day-loans page
    Given I want to launch the url "https://www.lendingstream.co.uk/loans/unsecured-loans/"
    Then I verify the url "https://www.lendingstream.co.uk/loans/unsecured-loans/"
    Then I verify <link> is present under "How much do unsecured loans cost?".
    Then I click on the <link> link present under "How much do unsecured loans cost?".
    Then I verify the <url>
    Examples:
      | link             | url                                                     |
      | payday loans     | https://www.lendingstream.co.uk/loans/payday-loans/     |
      | short-term loans | https://www.lendingstream.co.uk/loans/short-term-loans/ |