Feature: Lending stream debt management page test plan

  @LS @Desktop @MobileView @UI @debt-management @Body @content
  Scenario Outline: LS: Verify the body content in debt-management page
    Given I want to launch the url "https://www.lendingstream.co.uk/debt-management/"
    Then I verify the url "https://www.lendingstream.co.uk/debt-management/"
    Then I verify <content> is present
    Examples:
      | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | Debt Management and Short-term Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | Debt management advice introduction                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | If you’re having difficulty managing your debt, that can be stressful and exhausting. But you may be able to turn things around through a mixture of communication and perseverance.                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Please note that the following does not constitute financial advice. Always do your own research into financial matters to find the right solution for your personal circumstances. Also, while we are linking to some websites that you might find useful or interesting, we are not responsible for what they publish on their own websites.                                                                                                                                                                                                                                                            |
      | Prioritising debts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | Sites like the Money Advice Service recommend prioritising your debts into three different types.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | Priority debts (those with further consequences, such as court appearances, bankruptcy, bailiff action or removal of vital services like electricity)                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Non-priority debts (where you may not have immediate consequences, but missing payments could become more expensive or lead to court appearances etc later)                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | Debt emergencies(where you’re in immediate danger of a court appearance or bailiff action, etc).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | For debt emergencies, you should immediately look for free independent debt advice. You can find examples of this here.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | If you’re not at an emergency stage, you should list out all your outgoings and try to pay priority debts first, as these carry the most severe consequences. After this, if you want to reduce debt, it usually makes sense to overpay the most expensive debt first, paying the minimum amount elsewhere, so you don’t keep spiralling. Although it’s always worth checking if you are likely to receive a penalty for overpaying. It’s worth noting that the ‘most expensive debt’ may not actually be the biggest amount you owe, but the one that would work out most expensive if not repaid. |
      | Once this debt is repaid, you move onto the next most expensive debt and so on. If you have used high-cost short-term credit, then this may be one of the more expensive debts, as they’re designed for short-term use only.                                                                                                                                                                                                                                                                                                                                                                             |
      | Repayment plans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | If you’re having difficulty repaying a debt, it’s often worth contacting the lender. They may not be able to do anything, but they may be in a position to put you onto a repayment plan.                                                                                                                                                                                                                                                                                                                                                                                                               |
      | These obviously vary from lender to lender, but some will be able to freeze the amount of interest you owe and arrange a repayment plan to allow you to pay off the debt over a period of time with lower payments.                                                                                                                                                                                                                                                                                                                                                                                       |
      | If you do start a repayment plan, it’s important to stick to it. If you don’t, then the lender may go back to the original payment schedule. If you can now afford this, that’s hopefully fine – if not, it could just put you back at square one.                                                                                                                                                                                                                                                                                                                                                    |
      | Lending Stream and debt management                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | If you’ve taken out a loan with Lending Stream and are struggling with the repayments, please do call us. We understand that this can happen and we’ll try and help you find a solution and set up an affordable alternative payment plan. If we don’t know about your financial issues, we’ll continue collecting your next payment automatically, which could make your immediate situation worse                                                                                                                                                                                                   |
      | You can call us on 0203 808 4440 between 8am and 8pm. Please note that call charges apply and that standard charges from BT landlines, mobiles and other providers may vary.                                                                                                                                                                                                                                                                                                                                                                                                                              |
      | Links                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | You may find some of the following links useful. They’re not-for-profit organisations recommended by the Financial Conduct Authority and provide free, confidential and impartial debt advice.                                                                                                                                                                                                                                                                                                                                                                                                           |
      | The Financial Conduct Authority recommends contacting the following not-for-profit organisations for free, confidential and impartial debt advice, or for details of where to get such advice in your area.                                                                                                                                                                                                                                                                                                                                                                                               |
      | Money Advice Service                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | For free, unbiased and easy-to-access money tools, information and advice, visit www.moneyadviceservice.org.uk or phone 0300 500 5000 to speak to a Money Adviser.                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | Money Advice Scotland                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | If you live in Scotland, phone 0141 572 0237 or visit www.moneyadvicescotland.org.uk to find contact details for debt advice in your local area.                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | Citizens Advice Northern Ireland                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | If you live in Northern Ireland, phone 0800 028 1881, email debt.advice@citizensadvice.co.uk or visit www.citizensadvice.co.uk for debt advice.                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | AdviceUK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | Member centres offer debt advice including specialist advice for minority communities and people with disabilities - visit www.adviceuk.org.uk or phone 0300 777 0107.                                                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Christians Against Poverty (CAP)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | For free debt advice in your home, check post code coverage at www.capuk.org then call 0800 328 0006.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Citizens Advice                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | For advice and information on debt and other topics, visit your local Citizens Advice Bureau (address in the phone book) or go to www.adviceguide.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | National Debtline                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | If you live in England, Wales or Scotland phone 0808 808 4000 or visit www.nationaldebtline.org for debt advice and information.                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
      | StepChange Debt Charity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | For debt advice throughout the UK phone 0800 138 1111 or visit www.stepchange.org.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
      | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | You can find out more about alternative approaches to short-term financial issues by visiting the Money Advice Service.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
      | We don’t offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721.0%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed) you would owe 6 equal repayments of 64.44. You will repay 386.61 in total, there are no additional fees.                                                                                                                                                                                                                                                     |

  @LS @Desktop @MobileView @UI @debt-management @Body @link
  Scenario Outline: LS: Check all the links in debt-management page
    Given I want to launch the url "https://www.lendingstream.co.uk/debt-management/"
    Then I verify the url "https://www.lendingstream.co.uk/debt-management/"
    Then I verify <link> is present.
    Then I click on the <link> link
    Then I verify the <url>
    Examples:
      | link                           | url                                                                     |
      | Home                           | https://www.lendingstream.co.uk                                         |
      | here                           | https://www.moneyadviceservice.org.uk/en/tools/debt-advice-locator      |
      | www.moneyadviceservice.org.uk  | https://www.moneyadviceservice.org.uk/en                                |
      | www.moneyadvicescotland.org.uk | https://www.moneyadviceservice.org.uk/en                                |
      | www.citizensadvice.co.uk       | https://www.citizensadvice.co.uk/                                       |
      | www.adviceuk.org.uk            | https://www.adviceuk.org.uk/                                            |
      | www.capuk.org                  | https://capuk.org/                                                      |
      | www.adviceguide.org.uk         | https://www.citizensadvice.org.uk/                                      |
      | www.nationaldebtline.org       | https://www.nationaldebtline.org/                                       |
      | www.stepchange.org.            | https://www.stepchange.org/                                             |
      | moneyadviceservice.org.uk      | https://www.moneyadviceservice.org.uk/en                                |
      | Money Advice Service           | https://www.moneyadviceservice.org.uk/en                                |
      | Bad Credit Loans               | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 |
      | Quick Loans                    | https://www.lendingstream.co.uk/loans/quick-loans/                      |
      | Short-Term Loans               | https://www.lendingstream.co.uk/loans/short-term-loans/                 |
      | Compare Loans                  | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ |
      | Same Day Loans                 | https://www.lendingstream.co.uk/loans/same-day-loans/                   |
      | Unsecured Loans                | https://www.lendingstream.co.uk/loans/unsecured-loans/                  |