Feature: verify content in cookie-policy


    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @content
    Scenario Outline: LS: verifying the body content in cookie-policy
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify <content> is present

        Examples:
            | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | Cookie Policy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
            | Cookies and Web Beacons                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | This policy sets out our use of Cookies when you use our App, Our Sites and/or App Site. (as defined in our Privacy Policy) Please read it carefully as it explains how we and third parties may make use of your data collected by such Cookies. If you wish to understand how we make use of your data more generally please read our Privacy Policy for our App Site, Our Site and/or App.                                                                                                                                                                                                                                                                                                                                   |
            | If enabled, we may place cookies on your machine that store small amounts of data on your computer about your visit to any of the pages of the App Site and/or Our Site. Cookies assist us in tracking which of our features appeal the most to you and what content you may have viewed on past visits. When you visit Our Site or the App Site again, Cookies can enable us to customize our content according to your preferences. These cookies do not track user information in a way that identifies your name, and all our cookie data is encrypted and cannot be read by other websites. To find out more about accepting or refusing cookies please visit www.allaboutcookies.org.                                     |
            | Third-party tracking utility companies also assist us in tracking Our Site and/or the App Site activity and collecting Our Site and/or the App Site analytics data. We do not share any personal information with these third parties, but our tracking utility company uses session ID, persistent cookies to make it easier for you to navigate Our Site and/or the App Site. The use of cookies by our third-party tracking utility companies is not covered by our Privacy Policy. We do not have access or control over these cookies.                                                                                                                                                                                     |
            | We also use Google Analytics to collect non-personally identifiable information, in aggregate form, to understand website/page visit volumes in terms of source, geography, browser, etc.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | Google Analytics employs a software technology called web beacons, that help us better manage content on Our Site and/or the App Site by informing us what content is effective. Web beacons are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of Web users or responses to emails. In contrast to cookies, which are stored on a user's computer hard drive, web beacons are embedded invisibly on Web pages and are about the size of the period at the end of this sentence. Web beacons cannot be disabled in same manner as cookies may. We do not tie the information gathered by web beacons to our customers' personally identifiable information. |
            | Website: Cookies used by Lending Stream and Third Parties                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | Third Parties Using Cookies                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | Any information that we acquire about you using cookies or other web tools is subject to the same restrictions and conditions as any other information we collect about you.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | Cookies used by Hotjar:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | We make use of the Hotjar service to understand how users navigate around individual pages on our site. This information is anonymised and only used to monitor the performance of our site.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | Hotjar uses cookies and other technologies to collect data on our users' behavior and their devices (in particular device's IP address (captured and stored only in anonymized form), device screen size, device type (unique device identifiers), browser information, geographic location (country only), preferred language used to display our website). However, Hotjar stores the collected information in a pseudonymized user profile.                                                                                                                                                                                                                                                                                  |
            | Please see the cookie information below                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | Cookies used by Iovation:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | Names of Cookies: "__vstl", "io temp" and "token"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
            | What does the Cookie do? -                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | "_vstl" assists our business to prevent and detect fraud.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | "io temp" assists our business to prevent and detect fraud.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
            | "token" assists our business to prevent and detect fraud.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
            | How do we use this type of Cookie? - We use "__vstl", "io temp" and "token" to prevent and detect devices associated with fraudulent or other malicious activity and enable us to authenticate your account.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
            | What does the Cookie Collect? - The JavaScript collects information about the attributes of your device, which is like the types of information collected by many websites such as IP addresses, device type, browser type, screen resolution, operating system etc. It does not collect directly identifiable personal data, although it can collect your IP address. This information is then shared with a third-party service provider, Iovation Inc, for fraud prevention and account authentication purposes.                                                                                                                                                                                                             |
            | Cookie settings                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | You can block cookies by activating the setting on your browser that allows you to refuse the setting of all or some cookies. Please note that by disallowing cookies some functionality on the site may be restricted.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | Mobile App                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
            | Cookies used by Mobile server:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
            | Cookies used by Google Analytics:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
            | Cookies used by Piwik Analytics:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |


    #todo at the backend process

    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @content
    Scenario: LS: verifying the Contact US info in cookie-policy body
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "Contact Us info " is present

    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @table
    Scenario Outline: LS: verifying the table under Website: Cookies used by Lending Stream and Third Parties
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "table" is present.
        Then I verify the <Cookie> and <Description > of the Cookies used by Lending Stream and Third Parties table.

        Examples:
            | Cookie                                                                                                                                                                                                                                        | Description                                                                                                                               |
            | sessionid                                                                                                                                                                                                                                     | Identify customers when they login                                                                                                        |
            | csrftoken                                                                                                                                                                                                                                     | Offers protection against Cross-Site Request Forgery                                                                                      |
            | flavour, mob_num, m_override                                                                                                                                                                                                                  | Identify customers from mobile devices and render contents customized for mobile phone displays                                           |
            | lsrc, lsrc_detail, skey                                                                                                                                                                                                                       | Identify the source of the customer when he lands on the website for the first time and used for offering appropriate customer experience |
            | landDispRand, esignDispRand, thankuDispRand, applydisprand, mmrand, sid, homedisprand, valueid, uniqid, m-override, _C_mob_num, _C_flavor, appl_keyVal, dssrand, OptimizelySegments, optimizelyBuckets, optimizelyPendingLogEvents, unique_id | Displaying certain pages based on the variant chosen for the customer                                                                     |
            | token_direct , payment_direct                                                                                                                                                                                                                 | Dropped by the secure debit card gateway to prevent fraud                                                                                 |


    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @table
    Scenario Outline: LS: verifying the table under Third Parties Using Cookies
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "table" is present.
        Then I verify the <Cookie> and <Purpose > of the Third Parties Using Cookies table.

        Examples:
            | Cookie                          | Purpose                                                                |
            | sessionid                       | Used to maintain login session.                                        |
            | homeid                          | Unique id to identify arrival to website homepage                      |
            | Csrftoken, tmsid                | -To prevent forgery and fraud                                          |
            | trackingid                      | Combination of uniqid (permanent cookie) and valueid (session cookie)s |
            | Lsrc, lsrc_detail, lsrc_history | To know the source of website visitor                                  |
            | __utma, __utmb, __utmc, __utmz  | Google Analytics                                                       |
            | NRAGENT                         | New Relic                                                              |

    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @table
    Scenario Outline: LS: verifying the table under Cookies used by Hotjar:
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "table" is present.
        Then I verify the <Name> <Description> and <Expiration> of the  Please see the cookie information below table.

        Examples:
            | Name                       | Description                                                                                                                                                                                                 | Expiration |
            | _hjClosedSurveyInvites     | Hotjar cookie. This cookie is set once a visitor interacts with a Survey invitation modal popup. It is used to ensure that the same invite does not re-appear if it has already been shown.                 | 365 days   |
            | _hjDonePolls               | Hotjar cookie. This cookie is set once a visitor completes a poll using the Feedback Poll widget. It is used to ensure that the same poll does not re-appear if it has already been filled in.              | 365 days   |
            | _hjMinimizedPolls          | Hotjar cookie. This cookie is set once a visitor minimizes a Feedback Poll widget. It is used to ensure that the widget stays minimizes when the visitor navigates through your site.                       | 365 days   |
            | _hjDoneTestersWidgets      | Hotjar cookie. This cookie is set once a visitor submits their information in the Recruit User Testers widget. It is used to ensure that the same form does not re-appear if it has already been filled in. | 365 days   |
            | _hjMinimizedTestersWidgets | Hotjar cookie. This cookie is set once a visitor minimizes a Recruit User Testers widget. It is used to ensure that the widget stays minimizes when the visitor navigates through your site.                | 365 days   |
            | _hjIncludedInSample        | Hotjar cookie. This session cookie is set to let Hotjar know whether that visitor is included in the sample which is used to generate funnels.                                                              | 365 days   |

    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @table
    Scenario Outline: LS: verifying the table under Cookies used by Mobile server:
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "Cookies used by Mobile server" is present.
        Then I verify the table under "Cookies used by Mobile server"
        Then I verify the <Cookie> < Expiration Time> and <Description> of the table.

        Examples:
            | Cookie    | Expiration Time | Description                     |
            | sessionid | 30 mins         | Used to maintain login session. |

    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @table
    Scenario Outline: LS: verifying the table under Cookies used by Google Analytics:
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "Cookies used by Google Analytics:" is present.
        Then I verify the table under "Cookies used by Google Analytics:"
        Then I verify the <Cookie> <Expiration Time> and <Description> of the table.

        Examples:
            | Cookie | Expiration Time          | Description                                                                                                                                                                                                                                                                                   |
            | _ga    | 2 years                  | Used to distinguish users.                                                                                                                                                                                                                                                                    |
            | _gat   | 10 minutes               | Used to throttle request rate.                                                                                                                                                                                                                                                                |
            | __utma | 2 years from set/update  | Used to distinguish users and sessions. The cookie is created when the javascript library executes and no existing __utma cookies exists. The cookie is updated every time data is sent to Google Analytics.                                                                                  |
            | __utmt | 10 minutes               | Used to throttle request rate.                                                                                                                                                                                                                                                                |
            | __utmb | 30 mins from set/update  | Used to determine new sessions/visits. The cookie is created when the javascript library executes and no existing __utmb cookies exists. The cookie is updated every time data is sent to Google Analytics.                                                                                   |
            | __utmc | End of browser session   | Not used in ga.js. Set for interoperability with urchin.js. Historically, this cookie operated in conjunction with the __utmb cookie to determine whether the user was in a new session/visit.                                                                                                |
            | __utmz | 6 months from set/update | Stores the traffic source or campaign that explains how the user reached our App Site. The cookie is created when the javascript library executes and is updated every time data is sent to Google Analytics.                                                                                 |
            | __utmv | 2 years from set/update  | Used to store visitor-level custom variable data. This cookie is created when a developer uses the _setCustomVar method with a visitor level custom variable. This cookie was also used for the deprecated _setVar method. The cookie is updated every time data is sent to Google Analytics. |


    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @table
    Scenario Outline: LS: verifying the table under Cookies used by Piwik Analytics:
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "Cookies used by Piwik Analytics:" is present.
        Then I verify the table under "Cookies used by Piwik Analytics:"
        Then I verify the <Name> <Description> and <Expiration> of the table.

        Examples:
            | Cookie   | Expiration Time         | Description                  |
            | _pk_ref  | 2 years from set/update | Used to distinguish users.   |
            | _pk_cvar | 30 minutes              | Used for custom variables.   |
            | _pk_id   | 2 years from set/update | Used to distinguish device.  |
            | _pk_ses  | 30 minutes              | Used to distinguish session. |

    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @link
    Scenario Outline: LS: verifying the links in cookie-policy
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify <link> is present.
        Then I click on the <link> link
        Then I verify the <url>

        Examples:
            | Home                     | https://www.lendingstream.co.uk/                      |
            | Privacy Policy           | https://www.lendingstream.co.uk/legal/privacy-policy/ |
            | www.allaboutcookies.org. | http://www.allaboutcookies.org/                       |
            | Contact Us               | https://www.lendingstream.co.uk/contactus/            |

    @LS @Desktop @MobileView @UI @legal_cookie-policy @Body @legal @link
    Scenario: LS: cookie-policy: body : link present near please read our content
        Given I want to launch the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify the url "https://www.lendingstream.co.uk/legal/cookie-policy/"
        Then I verify "Privacy Policy" is present next to "please read our"
        Then I click on the "Privacy Policy" is present next to "please read our"
        Then I verify the "https://www.lendingstream.co.uk/legal/privacy-policy/" url is present