Feature: SEO verification on all static pages

 @Header @LS @Desktop @Manual @Signin
 Scenario: LS: Desktop : SEO : Verify SEO meta tag with name
  Given I want to open the <URL> page on any browser
   Then Right on the page and open "View page Source" option
   Then I Verify the Meta tag with name as <name>
   Then I Verify the Meta tag with content as <content>

     Examples:
     | URL                                                                     | name        | content                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk                                         | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk                                         | description | Lending Stream short term loans are a responsible payday loan alternative with 6 months to repay. Apply now, loans sent to your bank in 90 seconds.                                      |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 | description | Could bad credit loans help people who are looking for a loan with poor credit history? Find out more about bad credit loans with                                                        |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      | description | Looking for quick online loans? The Lending Stream process is designed to be a streamlined, stress-free and responsible alternative to quick loans                                       |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   | description | Apply for a same day loan with Lending Stream. No guarantor needed. Fast decision. If approved, we'll start transferring the money in minutes.                                           |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    | description | Lending Stream are direct lenders who provide 3 month loans as an alternative to payday loans or longer-term loans. Apply online for a quick decision                                    |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  | description | Lending Stream offers unsecured loans. We may be able to offer bad credit unsecured loans, subject to affordability. Learn more about unsecured loans & apply with Lending Stream.       |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   | description | Lending Stream offers info to help you compare payday loans. It's vital to look at the overall amount you are repaying and time-frame. Visit us to learn how to compare payday loans.    |
     | https://www.lendingstream.co.uk/about-us/                               | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/about-us/                               | description | Lending Stream is a trusted payday loan alternative, providing short-term loans to people across UK since 2008. New customers can apply up to £800.                                      |
     | https://www.lendingstream.co.uk/apr-explained/                          | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/apr-explained/                          | description | Annual Percentage Rate is an interest rate you pay on a loan. Lending Stream explains everything you need to know about APR and how to compare APRs on short term loans.                 |
     | https://www.lendingstream.co.uk/debt-management/                        | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/debt-management/                        | description | Are you looking for a debt management services, repayment plan? Visit our website to find some useful advice and solutions for your online debt management.                              |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   | description | You can apply for an additional short term loans with Lending Stream prior to paying off your current loan. We will not approve more than six total loans with us.                       |
     | https://www.lendingstream.co.uk/faqs/borrowing-limits/                  | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/borrowing-limits/                  | description | Loan application for short term cash loans. How much do you want to borrow? Apply online, loans streamed straight to your bank account within minutes of approval.                       |
     | https://www.lendingstream.co.uk/faqs/complaints/                        | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/complaints/                        | description | Your satisfaction is important to us. If you have a concern about our service or performance, we want to hear about it straightaway.                                                     |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        | description | To contact Lending Stream support, you can reach us at info@lendingstream.co.uk or by phone on 0203 808 4440. Our call centre representatives are available 08:00-20:00.                 |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           | description | We can't guarantee approval of your short-term loan until you've actually applied. Find out more about how we make our short-term loan decisions.                                        |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     | description | Our short-term loan approval process is simple, you apply loan, we analyze your situation and if approved loan streamed to your account.                                                 |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  | description | Do you want to know the eligibility requirements so you can apply for a short-term loan with Lending Stream? Find out more here                                                          |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         | description | Find out more about Lending Stream fees for six-month loans.                                                                                                                             |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 | description | Short term loan approval is based on a number of factors, and we have many elements to assess and consider when deciding loan request.                                                   |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        | description | We do everything we can to avoid loan risks by assessing your ability to repay a short-term loan. Be sure to carefully consider your ability to repay before you apply.                  |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         | description | Lending Stream online loan streaming process will initiate fund transfer to your account within minutes of approval.                                                                     |
     | https://www.lendingstream.co.uk/faqs/representative-example/            | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/representative-example/            | description | A representative example to help you understand all of the costs and charges of taking out a loan with                                                                                   |
     | https://www.lendingstream.co.uk/faqs/total-repayment-amount/            | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/faqs/total-repayment-amount/            | description | To contact Lending Stream support, you can reach us at info@lendingstream.co.uk or by phone on 0203 808 4440. Our call centre representatives are available 08:00-20:00.                 |
     | https://www.lendingstream.co.uk/loans/payday-loans/                     | viewport    | width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0                                                                                        |
     | https://www.lendingstream.co.uk/loans/payday-loans/                     | description | Lending Stream offer a fast, responsible alternative to payday loans from £50-£1500. Direct Lender. Cash sent to your bank in under 90 seconds if approved.                              |
     | https://www.lendingstream.co.uk/loans/short-term-loans/                 | viewport    | width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0                                                                                        |
     | https://www.lendingstream.co.uk/loans/short-term-loans/                 | description | Short term loans from a direct lender. £50 - £1500 with 6 months to repay. Cash sent to your bank in under 60 seconds. Apply now. Representative 1333% APR.                              |
     | https://www.lendingstream.co.uk/loans/                                  | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/loans/                                  | description | Lending Stream loan guides help you to figure out the kind of loans that suit you. What are short term loans, payday loans, etc? Find out here.                                          |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | description | Apply for a short term loan with Lending Stream and receive funds within 3 steps. Simple, concise and clear. Visit our website for more details.                                         |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    | description | Looking for Sunny Loans? Compare Sunny Vs Lending Stream. We offer a more flexible alternative to Sunny. Compare & apply now, cash sent to your bank in under 90 seconds.                |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  | description | Looking for loans like Satsuma? Compare Satsuma vs Lending Stream. We offer short term loans that are faster than Satsuma Loans, cash sent to your bank in under 90 seconds if agreed.   |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         | description | Looking for Loans like Pounds to Pocket? You can try Lending Stream as Pounds to Pocket is no longer lending. Lending Stream can send cash to your bank in under 90 seconds if approved. |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                | description | Looking for QuickQuid Loans? You can try Lending Stream as QuickQuid is no longer lending.You might find Lending Stream a better lender for you than QuickQuid ever were.                |
     | https://www.lendingstream.co.uk/compare-loans/                          | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/compare-loans/                          | description | Are you looking for Loans? Compare Lending Stream  loans with other lenders. Find the right one for you. Cash sent to your bank in under 90 seconds if approved.                         |
     | https://www.lendingstream.co.uk/how-it-works/                           | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/how-it-works/                           | description | Find out how Lending Stream works on cash loan streaming process for short term loans and payday loans. Apply online with representative 1333%                                           |
     | https://www.lendingstream.co.uk/sitemap/                                | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/sitemap/                                | description | You can reach us at info@lendingstream.co.uk or call us on 0203 808 4440. Our call centre representatives are available 08:00-20:00 to answer any queries.                               |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    | description | Lending Stream cookie policy helps you understand the cookies we use our App, our Sites and the purposes for which we use them.                                                          |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 | description | Lending Stream take consumer fraud very seriously, our customers are strongly advised to seek information by contacting our business office directly or online.                          |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   | description | Considering Lending Stream short-term loan? Read our privacy policy  to understand our views and practices.                                                                              |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     | viewport    | width=device-width, height=device-height, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0                                                                      |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     | description | Please read the Terms of Use carefully Lending Stream services and products that we provide on website are intended for UK residents over the age of 18 only                             |


 @Header @LS @Desktop @Manual @Signin
 Scenario: LS: Desktop : SEO : Verify SEO meta tag with property
  Given I want to open the <URL> page on any browser
   Then Right on the page and open "View page Source" option
   Then I Verify the Meta tag with property as <property>
   Then I Verify the Meta tag with content as <content>

     Examples:
     | URL                                                                     | property       | content                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk                                         | og:title       | Lending Stream Loans up to £1,500, Direct Lender, Apply Online                                                                                                                           |
     | https://www.lendingstream.co.uk                                         | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk                                         | og:url         | https://www.lendingstream.co.uk/                                                                                                                                                         |
     | https://www.lendingstream.co.uk                                         | og:description | Lending Stream short term loans are a responsible payday loan alternative with 6 months to repay. Apply now, loans sent to your bank in 90 seconds.                                      |
     | https://www.lendingstream.co.uk                                         | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 | og:title       | Can you get Bad Credit Loans from UK Direct Lenders?                                                                                                                                     |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 | og:url         | https://www.lendingstream.co.uk/loans/bad-credit-loans/                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 | og:description | Could bad credit loans help people who are looking for a loan with poor credit history? Find out more about bad credit loans with                                                        |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      | og:title       | Quick Loans UK, Online Instalment Loans                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      | og:url         | https://www.lendingstream.co.uk/loans/quick-loans/                                                                                                                                       |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      | og:description | Looking for quick online loans? The Lending Stream process is designed to be a streamlined, stress-free and responsible alternative to quick loans                                       |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   | og:title       | Same Day Loans Up To £1500, Apply Online                                                                                                                                                 |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   | og:url         | https://www.lendingstream.co.uk/loans/same-day-loans/                                                                                                                                    |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   | og:description | Apply for a same day loan with Lending Stream. No guarantor needed. Fast decision. If approved, we'll start transferring the money in minutes.                                           |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    | og:title       | 3 Month Loans Direct Lenders, Apply Online                                                                                                                                               |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    | og:url         | https://www.lendingstream.co.uk/loans/3-month-loans/                                                                                                                                     |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    | og:description | Lending Stream are direct lenders who provide 3 month loans as an alternative to payday loans or longer-term loans. Apply online for a quick decision                                    |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  | og:title       | Unsecured Loans - Apply Now                                                                                                                                                              |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  | og:url         | https://www.lendingstream.co.uk/loans/unsecured-loans/                                                                                                                                   |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  | og:description | Lending Stream offers unsecured loans. We may be able to offer bad credit unsecured loans, subject to affordability. Learn more about unsecured loans & apply with Lending Stream.       |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   | og:title       | Compare Payday Loans, Lenders Comparison                                                                                                                                                 |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   | og:url         | https://www.lendingstream.co.uk/compare-payday-loans/                                                                                                                                    |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   | og:description | Lending Stream offers info to help you compare payday loans. It's vital to look at the overall amount you are repaying and time-frame. Visit us to learn how to compare payday loans.    |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/about-us/                               | og:title       | About us                                                                                                                                                                                 |
     | https://www.lendingstream.co.uk/about-us/                               | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/about-us/                               | og:url         | https://www.lendingstream.co.uk/about-us/                                                                                                                                                |
     | https://www.lendingstream.co.uk/about-us/                               | og:description | Lending Stream is a trusted payday loan alternative, providing short-term loans to people across UK since 2008. New customers can apply up to £800.                                      |
     | https://www.lendingstream.co.uk/about-us/                               | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/apr-explained/                          | og:title       | What is APR? How APR Works                                                                                                                                                               |
     | https://www.lendingstream.co.uk/apr-explained/                          | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/apr-explained/                          | og:url         | https://www.lendingstream.co.uk/apr-explained/                                                                                                                                           |
     | https://www.lendingstream.co.uk/apr-explained/                          | og:description | Annual Percentage Rate is an interest rate you pay on a loan. Lending Stream explains everything you need to know about APR and how to compare APRs on short term loans.                 |
     | https://www.lendingstream.co.uk/apr-explained/                          | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/debt-management/                        | og:title       | Loan Debt - Management, Repayment Plans & Advice                                                                                                                                         |
     | https://www.lendingstream.co.uk/debt-management/                        | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/debt-management/                        | og:url         | https://www.lendingstream.co.uk/debt-management/                                                                                                                                         |
     | https://www.lendingstream.co.uk/debt-management/                        | og:description | Are you looking for a debt management services, repayment plan? Visit our website to find some useful advice and solutions for your online debt management.                              |
     | https://www.lendingstream.co.uk/debt-management/                        | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   | og:title       | Multiple Loans - About Applying For An Additional Loan                                                                                                                                   |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   | og:url         | https://www.lendingstream.co.uk/faqs/additional-loan/                                                                                                                                    |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   | og:description | You can apply for an additional short term loans with Lending Stream prior to paying off your current loan. We will not approve more than six total loans with us.                       |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/borrowing-limits/                  | og:title       | TITLE                                                                                                                                                                                    |
     | https://www.lendingstream.co.uk/faqs/borrowing-limits/                  | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/borrowing-limits/                  | og:url         | https://www.lendingstream.co.uk/faqs/borrowing-limits/                                                                                                                                   |
     | https://www.lendingstream.co.uk/faqs/borrowing-limits/                  | og:description | Loan application for short term cash loans. How much do you want to borrow? Apply online, loans streamed straight to your bank account within minutes of approval.                       |
     | https://www.lendingstream.co.uk/faqs/borrowing-limits/                  | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/complaints/                        | og:title       | Making a Complaint                                                                                                                                                                       |
     | https://www.lendingstream.co.uk/faqs/complaints/                        | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/complaints/                        | og:url         | https://www.lendingstream.co.uk/faqs/complaints/                                                                                                                                         |
     | https://www.lendingstream.co.uk/faqs/complaints/                        | og:description | Your satisfaction is important to us. If you have a concern about our service or performance, we want to hear about it straightaway.                                                     |
     | https://www.lendingstream.co.uk/faqs/complaints/                        | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        | og:title       | Contact Us - Online or Phone                                                                                                                                                             |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        | og:url         | https://www.lendingstream.co.uk/faqs/contact-us/                                                                                                                                         |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        | og:description | To contact Lending Stream support, you can reach us at info@lendingstream.co.uk or by phone on 0203 808 4440. Our call centre representatives are available 08:00-20:00.                 |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           | og:title       | Can You Guarantee Loan Approval?                                                                                                                                                         |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           | og:url         | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/                                                                                                                            |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           | og:description | We can't guarantee approval of your short-term loan until you've actually applied. Find out more about how we make our short-term loan decisions.                                        |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     | og:title       | Loan Approval decisions                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     | og:url         | https://www.lendingstream.co.uk/faqs/loan-approval/                                                                                                                                      |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     | og:description | Our short-term loan approval process is simple, you apply loan, we analyze your situation and if approved loan streamed to your account.                                                 |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  | og:title       | Am I eligible to apply short term loans?                                                                                                                                                 |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  | og:url         | https://www.lendingstream.co.uk/faqs/loan-eligibility/                                                                                                                                   |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  | og:description | Do you want to know the eligibility requirements so you can apply for a short-term loan with Lending Stream? Find out more here                                                          |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         | og:title       | Loan Fees - What Do We Charge?                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         | og:url         | https://www.lendingstream.co.uk/faqs/loan-fees/                                                                                                                                          |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         | og:description | Find out more about Lending Stream fees for six-month loans.                                                                                                                             |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 | og:title       | Why Was My Loan Application Declined?                                                                                                                                                    |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 | og:url         | https://www.lendingstream.co.uk/faqs/loan-not-approved/                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 | og:description | Short term loan approval is based on a number of factors, and we have many elements to assess and consider when deciding loan request.                                                   |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        | og:title       | Loan Risks - What To Be Aware Of                                                                                                                                                         |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        | og:url         | https://www.lendingstream.co.uk/faqs/loan-risks/                                                                                                                                         |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        | og:description | We do everything we can to avoid loan risks by assessing your ability to repay a short-term loan. Be sure to carefully consider your ability to repay before you apply.                  |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         | og:title       | What is Loan Streaming                                                                                                                                                                   |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         | og:url         | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/                                                                                                                          |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         | og:description | Lending Stream online loan streaming process will initiate fund transfer to your account within minutes of approval.                                                                     |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/representative-example/            | og:title       | Loans Representative Example                                                                                                                                                             |
     | https://www.lendingstream.co.uk/faqs/representative-example/            | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/representative-example/            | og:url         | https://www.lendingstream.co.uk/faqs/representative-example/                                                                                                                             |
     | https://www.lendingstream.co.uk/faqs/representative-example/            | og:description | A representative example to help you understand all of the costs and charges of taking out a loan with                                                                                   |
     | https://www.lendingstream.co.uk/faqs/representative-example/            | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/faqs/total-repayment-amount/            | og:title       | How can I contact you if I have a problem?                                                                                                                                               |
     | https://www.lendingstream.co.uk/faqs/total-repayment-amount/            | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/faqs/total-repayment-amount/            | og:url         | https://www.lendingstream.co.uk/faqs/contact-us/                                                                                                                                         |
     | https://www.lendingstream.co.uk/faqs/total-repayment-amount/            | og:description | To contact Lending Stream support, you can reach us at info@lendingstream.co.uk or by phone on 0203 808 4440. Our call centre representatives are available 08:00-20:00.                 |
     | https://www.lendingstream.co.uk/faqs/total-repayment-amount/            | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/payday-loans/                     | og:title       | Payday Loans Alternative £50 - £1500, Apply Online                                                                                                                                       |
     | https://www.lendingstream.co.uk/loans/payday-loans/                     | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/loans/payday-loans/                     | og:url         | https://www.lendingstream.co.uk/loans/payday-loans/                                                                                                                                      |
     | https://www.lendingstream.co.uk/loans/payday-loans/                     | og:description | Lending Stream offer a fast, responsible alternative to payday loans from £50-£1500. Direct Lender. Cash sent to your bank in under 90 seconds if approved.                              |
     | https://www.lendingstream.co.uk/loans/payday-loans/                     | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/short-term-loans/                 | og:title       | Short Term Loans Online, Direct Lenders                                                                                                                                                  |
     | https://www.lendingstream.co.uk/loans/short-term-loans/                 | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/loans/short-term-loans/                 | og:url         | https://www.lendingstream.co.uk/                                                                                                                                                         |
     | https://www.lendingstream.co.uk/loans/short-term-loans/                 | og:description | Short term loans from a direct lender. £50 - £1500 with 6 months to repay. Cash sent to your bank in under 60 seconds. Apply now. Representative 1333% APR.                              |
     | https://www.lendingstream.co.uk/loans/short-term-loans/                 | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:title       | Apply for Loans Online                                                                                                                                                                   |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:url         | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:description | Lending Stream loan guides help you to figure out the kind of loans that suit you.What are short term loans, payday loans, etc? Find out here.                                           |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:title       | Compare Short Term Loans, Lenders Comparison                                                                                                                                             |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:url         | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:description | Apply for a short term loan with Lending Stream and receive funds within 3 steps. Simple, concise and clear. Visit our website for more details.                                         |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    | og:title       | Sunny Loans Comparison                                                                                                                                                                   |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    | og:url         | https://www.lendingstream.co.uk/compare-loans/sunny/                                                                                                                                     |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    | og:description | Looking for Sunny Loans? Compare Sunny Vs Lending Stream. We offer a more flexible alternative to Sunny. Compare & apply now, cash sent to your bank in under 90 seconds.                |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  | og:title       | Satsuma Loans Comparison                                                                                                                                                                 |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  | og:url         | https://www.lendingstream.co.uk/compare-loans/satsuma/                                                                                                                                   |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  | og:description | Looking for loans like Satsuma? Compare Satsuma vs Lending Stream. We offer short term loans that are faster than Satsuma Loans, cash sent to your bank in under 90 seconds if agreed.   |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         | og:title       | As Pounds to Pocket is no longer lending                                                                                                                                                 |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         | og:url         | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/                                                                                                                          |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         | og:description | Looking for Loans like Pounds to Pocket? You can try Lending Stream as Pounds to Pocket is no longer lending. Lending Stream can send cash to your bank in under 90 seconds if approved. |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                | og:title       | As QuickQuid is no longer lending                                                                                                                                                        |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                | og:url         | https://www.lendingstream.co.uk/compare-loans/quickquid/                                                                                                                                 |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                | og:description | Looking for QuickQuid Loans? You can try Lending Stream as QuickQuid is no longer lending.You might find Lending Stream a better lender for you than QuickQuid ever were.                |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/                          | og:title       | Compare Loans & Lenders                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/compare-loans/                          | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/                          | og:url         | https://www.lendingstream.co.uk/compare-loans/                                                                                                                                           |
     | https://www.lendingstream.co.uk/compare-loans/                          | og:description | Are you looking for Loans? Compare Lending Stream  loans with other lenders. Find the right one for you. Cash sent to your bank in under 90 seconds if approved.                         |
     | https://www.lendingstream.co.uk/compare-loans/                          | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/how-it-works/                           | og:title       | How it Works, Loan Application Process                                                                                                                                                   |
     | https://www.lendingstream.co.uk/how-it-works/                           | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/how-it-works/                           | og:url         | https://www.lendingstream.co.uk/how-it-works/                                                                                                                                            |
     | https://www.lendingstream.co.uk/how-it-works/                           | og:description | Find out how Lending Stream works on cash loan streaming process for short term loans and payday loans. Apply online with representative 1333%                                           |
     | https://www.lendingstream.co.uk/how-it-works/                           | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/sitemap/                                | og:title       | Sitemap                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/sitemap/                                | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/sitemap/                                | og:url         | https://www.lendingstream.co.uk/sitemap/                                                                                                                                                 |
     | https://www.lendingstream.co.uk/sitemap/                                | og:description | You can reach us at info@lendingstream.co.uk or call us on 0203 808 4440. Our call centre representatives are available 08:00-20:00 to answer any queries.                               |
     | https://www.lendingstream.co.uk/sitemap/                                | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    | og:title       | Cookie Policy                                                                                                                                                                            |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    | og:url         | https://www.lendingstream.co.uk/legal/cookie-policy/                                                                                                                                     |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    | og:description | Lending Stream cookie policy helps you understand the cookies we use our App, our Sites and the purposes for which we use them.                                                          |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 | og:title       | Fraud Disclaimer                                                                                                                                                                         |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 | og:url         | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                                                                                                                                  |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 | og:description | Lending Stream take consumer fraud very seriously, our customers are strongly advised to seek information by contacting our business office directly or online.                          |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   | og:title       | Privacy Policy                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   | og:url         | https://www.lendingstream.co.uk/legal/privacy-policy/                                                                                                                                    |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   | og:description | Considering Lending Stream short-term loan? Read our privacy policy  to understand our views and practices.                                                                              |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   | og:type        | website                                                                                                                                                                                  |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     | og:title       | Terms of Use                                                                                                                                                                             |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     | og:site_name   | Lending Stream                                                                                                                                                                           |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     | og:url         | https://www.lendingstream.co.uk/legal/terms-of-use/                                                                                                                                      |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     | og:description | Please read the Terms of Use carefully Lending Stream services and products that we provide on website are intended for UK residents over the age of 18 only                             |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     | og:type        | website                                                                                                                                                                                  |

 @Header @LS @Desktop @Manual @Signin
 Scenario: LS: Desktop : SEO : Verify SEO link tag with canonical url
  Given I want to open the <URL> page on any browser
   Then Right on the page and open "View page Source" option
   Then I Verify the link tag with canonical url as <URL>

     Examples:
     | URL                                                                     |
     | https://www.lendingstream.co.uk                                         |
     | https://www.lendingstream.co.uk/loans/bad-credit-loans/                 |
     | https://www.lendingstream.co.uk/loans/quick-loans/                      |
     | https://www.lendingstream.co.uk/loans/same-day-loans/                   |
     | https://www.lendingstream.co.uk/loans/3-month-loans/                    |
     | https://www.lendingstream.co.uk/loans/unsecured-loans/                  |
     | https://www.lendingstream.co.uk/compare-payday-loans/                   |
     | https://www.lendingstream.co.uk/about-us/                               |
     | https://www.lendingstream.co.uk/apr-explained/                          |
     | https://www.lendingstream.co.uk/debt-management/                        |
     | https://www.lendingstream.co.uk/faqs/additional-loan/                   |
     | https://www.lendingstream.co.uk/faqs/complaints/                        |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        |
     | https://www.lendingstream.co.uk/faqs/guarantee-loan-approval/           |
     | https://www.lendingstream.co.uk/faqs/loan-approval/                     |
     | https://www.lendingstream.co.uk/faqs/loan-eligibility/                  |
     | https://www.lendingstream.co.uk/faqs/loan-fees/                         |
     | https://www.lendingstream.co.uk/faqs/loan-not-approved/                 |
     | https://www.lendingstream.co.uk/faqs/loan-risks/                        |
     | https://www.lendingstream.co.uk/faqs/loan-streaming-in-minutes/         |
     | https://www.lendingstream.co.uk/faqs/representative-example/            |
     | https://www.lendingstream.co.uk/faqs/contact-us/                        |
     | https://www.lendingstream.co.uk/loans/                                  |
     | https://www.lendingstream.co.uk/compare-loans/short-term-loans-compare/ |
     | https://www.lendingstream.co.uk/compare-loans/sunny/                    |
     | https://www.lendingstream.co.uk/compare-loans/satsuma/                  |
     | https://www.lendingstream.co.uk/compare-loans/pounds-to-pocket/         |
     | https://www.lendingstream.co.uk/compare-loans/quickquid/                |
     | https://www.lendingstream.co.uk/compare-loans/                          |
     | https://www.lendingstream.co.uk/how-it-works/                           |
     | https://www.lendingstream.co.uk/sitemap/                                |
     | https://www.lendingstream.co.uk/legal/cookie-policy/                    |
     | https://www.lendingstream.co.uk/legal/fraud-disclaimer/                 |
     | https://www.lendingstream.co.uk/legal/privacy-policy/                   |
     | https://www.lendingstream.co.uk/legal/terms-of-use/                     |
