Feature: verify how-it-works page content and links

@LS @Desktop @MobileView @UI @how-it-works @Body @content
Scenario: LS: how-it-works_page: verify the body content of how it works page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/how-it-works"
    Then user verifies 'how-it-works' URL
    Then verifies content of 'how-it-works' 
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | How It Works                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | You apply ● Instant Decision ● Fast Fund Transfer                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | How to apply for loan streaming                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | You apply                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | Applying for short-term loan streaming is simple. Just choose how much you want to borrow and fill in your personal, banking and employment details. It usually takes 5 minutes** or so.                                                                                                                                                                                                                                                                                    |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                               |
     | ​​​​​​For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | **Application times may vary. Please carefully fill out the application and consider each section before proceeding with the application.                                                                                                                                                                                                                                                                                                                                   |
     | You get your decision                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
     | We'll run your application info through our algorithm, taking into account your circumstances and not just your credit rating. In most cases, we'll give you an instant decision and let you know how much you can borrow.                                                                                                                                                                                                                                                  |
     | Your loan gets streamed right to your account                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Just give us your bank account details as part of the application, and we'll start streaming the cash to your bank in under 90 seconds                                                                                                                                                                                                                                                                                                                                      |
     | Take control of your repayments                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | There are two ways we can do the repayments. Whatever works best for you - it's your call.                                                                                                                                                                                                                                                                                                                                                                                  |
     | We take out the amount each month on a specified date (and we'll remind you when we're about to do it, so it's not a surprise)                                                                                                                                                                                                                                                                                                                                              |
     | You can make individual payments through your account, either on the website or by calling us on 0203 808 4440#                                                                                                                                                                                                                                                                                                                                                             |
     | We'll help make sure you know what you're doing throughout as well. We'll keep in contact with you with information about how to avoid problems and help keep your financial position positive.                                                                                                                                                                                                                                                                             |
     | Are you eligible?                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | If you want to apply for a short-term loan with Lending Stream, you'll need to be at least 18 years old, a UK resident and in regular employment earning at least £400 a month. You'll also need a valid debit card and active bank account.                                                                                                                                                                                                                                |
     | Or you can get started with our online application and get an instant decision.                                                                                                                                                                                                                                                                                                                                                                                             |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | What is a representative example of a Lending Stream loan?                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | A representative example shows you the terms of our typical loan (offered to more than 51% of applicants) and the cost of credit in accordance with the Consumer Credit (Advertisements) Regulations 2010.                                                                                                                                                                                                                                                                  |
     | How does continuous payment authority work?                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Continuous Payment Authority (CPA) is a way of making payments on your loan. It means you give us permission to collect payments automatically from the bank account that's linked to your debit card. This is set up when you apply and can help you avoid missed payments.                                                                                                                                                                                                |
     | You can cancel CPA at any time by asking us or contacting your bank. If you do so, you'll need to arrange payments in a different way, such as online payments via the Lending Stream website, a standing bank order, or even posting a cheque. If your loan payment is outstanding, please contact us so we can help you set something else up.                                                                                                                            |
     | What loan fees do you charge?                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | The only fees we charge are for late payments:                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | The first time you miss a payment, we may apply a late payment charge of up to £15                                                                                                                                                                                                                                                                                                                                                                                          |
     | If you miss any further payments, we may charge you again. The combined amount of all charges we make (including the first one) will not exceed £15                                                                                                                                                                                                                                                                                                                         |
     | What happens if I can't pay back the loan?                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | We'll try to avoid putting you in the position - this is why we don't guarantee you'll be accepted. But we understand that things do go wrong sometimes. If you have any problems, please contact us and we'll work with you to arrange an alternative repayment plan that may suit you better.                                                                                                                                                                             |
     | Also, if you find it useful, you can contact free debt advice providers moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                          |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Learn more about the cost of your loan, default charges, risks and prepayments.                                                                                                                                                                                                                                                                                                                                                                                             |
     | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short-term financial needs but which is not appropriate for longer-term borrowing or if you are in financial difficulty. All loan applications are subject to status checks, terms and conditions, and to satisfactory passage of checks on credit-worthiness and affordability. |
     | More information on cash loans                                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | Upon Approval At Lending Stream, you will get                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Fund Transfer                                                                                                                                                                                                                                                                                                                                                                                                                                                               |  
     | Cash sent to your bank in under 90 seconds                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | 24/7 Deposits                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Even on bank holidays                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
     | Simple Payments                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | Automatically withdrawn from your bank                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                                                                       |

@LS @how-it-works @UI @Desktop @Mobileview @Body @table 
Scenario: LS: how-it-works_page: verify the table content of how it works page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/how-it-works"
    Then user verifies 'how-it-works' URL
    Then verify 'Representative example' heading is present
    Then verify content of Representative example table
        | left_value             | right_value |
        | Annual Interest Rate   | 292.0%      |
        | Total amount of credit | £200        |
        | Representative APR     | 1333%       |
        | Duration of agreement  | 6 months    |
        | Total amount payable   | £386.61     |
        | Total charge of credit | £186.61     |
        | Six repayments of:     | £64.44      |

@LS @Desktop @UI @how-it-works @Body @link 
Scenario: LS: how-it-works_page: verify the links of how it works page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/how-it-works"
    Then user verifies 'how-it-works' URL
    Then verify links and urls of 'how-it-works' page
     | link                                                            | url                                                                |
     | Home                                                            | https://preprod2-re.globalanalytics.in/                            |
     | How It Works                                                    | https://preprod2-re.globalanalytics.in/how-it-works                |
     | Apply Now                                                       | https://preprod2-re.globalanalytics.in/application/apply           |
     | moneyadviceservice.org.uk                                       | https://www.moneyadviceservice.org.uk/en                           |
     | Read our blog                                                   | https://www.lendingstream.co.uk/blog/                              |
     | Sign up for our newsletter                                      | https://www.lendingstream.co.uk/consumer/subscribe/                |
     | Connect with us on social media                                 | https://www.facebook.com/lendingstream                             |      
     | short-term loan                                                 | https://preprod2-re.globalanalytics.in/loans/short-term-loans/     |
     | Apply Now                                                       | https://preprod2-re.globalanalytics.in/application/apply/          |
     | contact us                                                      | https://preprod2-re.globalanalytics.in/contactus/                  |
     | contact us                                                      | https://preprod2-re.globalanalytics.in/contactus/                  |
     | moneyadviceservice.org.uk.                                      | https://www.moneyadviceservice.org.uk/en                           |
     | Apply Now                                                       | https://preprod2-re.globalanalytics.in/application/apply/          |
     | cost of your loan                                               | https://preprod2-re.globalanalytics.in/faqs/representative-example/|   
     | default charges                                                 | https://preprod2-re.globalanalytics.in/faqs/loan-fees/             |
     | risks and prepayments                                           | https://preprod2-re.globalanalytics.in/faqs/loan-risks/            |
     | What risks I should be aware of when I take out a loan?         | https://preprod2-re.globalanalytics.in/faqs/loan-risks/            |
     | How much money can I borrow if I'm approved?                    | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/      |
     | What loan fees do you charge?                                   | https://preprod2-re.globalanalytics.in/faqs/loan-fees/             |
     | What is the total amount I'll pay for a Lending Stream loan?    | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/       |
     | How does continuous payment authority work?                     | https://preprod2-re.globalanalytics.in/faqs/#continuous-payment-authority |
     | What happens if I can't pay back the loan?                      | https://preprod2-re.globalanalytics.in/faqs/#cant-repay-loan              |
     | Do you run a credit check and will that impact my credit score? | https://preprod2-re.globalanalytics.in/faqs/#credit-check                 |
     | Read more of our FAQ's                                          | https://preprod2-re.globalanalytics.in/faqs/                              |


@LS @MobileView @UI @how-it-works @Body @link 
Scenario: LS: how-it-works_page: verify the links of how it works page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/how-it-works"
    Then user verifies 'how-it-works' URL
    Then verify links and urls of 'how-it-works' page
     | link                                                            | url                                                                |
     | Home                                                            | https://preprod2-re.globalanalytics.in/                            |
     | How It Works                                                    | https://preprod2-re.globalanalytics.in/how-it-works                |
     | Apply Now                                                       | https://preprod2-re.globalanalytics.in/application/apply           |
     | moneyadviceservice.org.uk                                       | https://www.moneyadviceservice.org.uk/en                           |
     | Read our blog                                                   | https://www.lendingstream.co.uk/blog/                              |
     | Sign up for our newsletter                                      | https://www.lendingstream.co.uk/consumer/subscribe/                |
     | Connect with us on social media                                 | https://m.facebook.com/lendingstream                               |      
     | short-term loan                                                 | https://preprod2-re.globalanalytics.in/loans/short-term-loans/     |
     | Apply Now                                                       | https://preprod2-re.globalanalytics.in/application/apply/          |
     | contact us                                                      | https://preprod2-re.globalanalytics.in/contactus/                  |
     | contact us                                                      | https://preprod2-re.globalanalytics.in/contactus/                  |
     | moneyadviceservice.org.uk.                                      | https://www.moneyadviceservice.org.uk/en                           |
     | Apply Now                                                       | https://preprod2-re.globalanalytics.in/application/apply/          |
     | cost of your loan                                               | https://preprod2-re.globalanalytics.in/faqs/representative-example/|   
     | default charges                                                 | https://preprod2-re.globalanalytics.in/faqs/loan-fees/             |
     | risks and prepayments                                           | https://preprod2-re.globalanalytics.in/faqs/loan-risks/            |
     | What risks I should be aware of when I take out a loan?         | https://preprod2-re.globalanalytics.in/faqs/loan-risks/            |
     | How much money can I borrow if I'm approved?                    | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/      |
     | What loan fees do you charge?                                   | https://preprod2-re.globalanalytics.in/faqs/loan-fees/             |
     | What is the total amount I'll pay for a Lending Stream loan?    | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/       |
     | How does continuous payment authority work?                     | https://preprod2-re.globalanalytics.in/faqs/#continuous-payment-authority |
     | What happens if I can't pay back the loan?                      | https://preprod2-re.globalanalytics.in/faqs/#cant-repay-loan              |
     | Do you run a credit check and will that impact my credit score? | https://preprod2-re.globalanalytics.in/faqs/#credit-check                 |
     | Read more of our FAQ's                                          | https://preprod2-re.globalanalytics.in/faqs/                              |
