Feature: Lending stream payday-loans page test plan

@LS @Desktop @MobileView @UI @payday-loans @Body @content 
Scenario:LS: payday-loans: Verify the static content in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/payday-loans/"
    Then user verifies 'payday-loans' URL
    Then verify the content of 'payday-loans' page 
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                            |
     | ✓ Quick application       ✓ Fast cash transfer                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Payday loans with Lending Stream                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | Looking for a payday loan? With payday loans, you may only have a month to repay. With Lending Stream, you can repay over a longer period. You’ll get a fast decision and cash sent to your bank in 90 seconds if you’re approved.                                                                                                                                                                                                                 |
     | Lending Stream is a short-term loan of up to £1500, repayable over 6 months. We’ve provided over 3 million loans and 97% of customers recommend us.                                                                                                                                                                                                                                                                                                |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | Warning: Late repayment can cause you serious money problems. For help go to moneyadviceservice.org.uk                                                                                                                                                                                                                                                                                                                                             |
     | Payday loans online                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Some payday lenders let you apply online and some don’t. Applying for our 6 month loan is easy and all done online. You’ll also find out if you are approved really fast. You don’t need to wait for your cash if you’re approved either. Lending Stream sends cash to your bank in under 90 seconds.                                                                                                                                              |
     | Payday loans direct lender                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | It can be annoying when you spend ages applying for a loan, just to find out it wasn’t even with a lender! It was just a broker that wasn’t clear about who they were. We’re a direct lender, so if you apply to us, we’ll be the ones lending to you. It’s that simple.                                                                                                                                                                           |
     | This also means that your data isn’t being sent to multiple companies, so you’ll have more control over how your information is used. We also definitely don’t charge you to apply.                                                                                                                                                                                                                                                                |
     | How Lending Stream works                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | We take lending decisions seriously, but we know the process has to be straightforward too. Even though we take lots of factors into account, we just have one form for you to fill in.                                                                                                                                                                                                                                                            |
     | When you apply, you’ll be asked for information about yourself, your income and your expenses.                                                                                                                                                                                                                                                                                                                                                     |
     | We’ll use your information to check you can afford the loan, now as well as for the next 6 months. If you’re approved, you’ll be offered a loan. If you accept the offer, we’ll send the cash straight to your bank (in under 90 seconds).                                                                                                                                                                                                         |
     | Here’s a quick video explaining how it all works:                                                                                                                                                                                                                                                                                                                                                                                                  |
     | Want to learn more? Check out our FAQs below.                                                                                                                                                                                                                                                                                                                                                                                                      |
     | How can I save money on a payday loan?                                                                                                                                                                                                                                                                                                                                                                                                             |
     | We give you 6 months to pay so that repayments on your loan are affordable. But if you find you can pay back earlier, you can save money on interest. You won’t be charged any early repayment fees either. On average, customers pay us back in under 4 months.                                                                                                                                                                                   |
     | Read more about repaying early in our FAQs below.                                                                                                                                                                                                                                                                                                                                                                                                  |
     | Payday loans for bad credit                                                                                                                                                                                                                                                                                                                                                                                                                        |
     | Are you looking for a bad credit loan? At Lending Stream, we’ll look at your wider financial situation rather than just your credit score. This may include what your finances are like right now, to help us work out if you can afford the loan or not and if you are likely to afford it over the next 6 months.                                                                                                                                |
     | It’s important to make sure you can afford a loan before you apply. This means taking a look at your income and outgoings each month. If you’re looking for a traditional payday loan, it might be expensive to repay the entire amount in one or two payments. So, if you’re looking for a loan online, apply now with Lending Stream. You might find that repaying your loan over 6 months work better for you.                                  |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | Payday loans for emergencies                                                                                                                                                                                                                                                                                                                                                                                                                       |
     | If you’re looking for a payday loan, it’s probably for something urgent. We understand that sometimes emergencies happen, and money is needed fast. This is why we’ve made sure our process works quickly (while still checking the loan is right for you).                                                                                                                                                                                        |
     | Even though you have 6 months to repay, Lending Stream sends the money to your bank in 90 seconds of you agreeing to the loan. So if you’re dealing with an emergency and need a fast loan, you might be able to get the cash you need with Lending Stream.                                                                                                                                                                                        |
     | Why Lending Stream?                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Fast                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Cash to your bank in under 90 seconds                                                                                                                                                                                                                                                                                                                                                                                                              |
     | Convenient                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | Secure application and fast decision                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Affordable                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | Six months to repay                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Trusted                                                                                                                                                                                                                                                                                                                                                                                                                                            |
     | High rating on Reviews.co.uk                                                                                                                                                                                                                                                                                                                                                                                                                       |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | What are payday loans?                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | Payday loans are a type of short-term loan, usually for a month or less, that you pay off when you get paid. They are emergency loans to tide you over to your next payday.                                                                                                                                                                                                                                                                        |
     | ‘Payday loans’ is sometimes used to describe short term, unsecured loans in general. More people are using products like Lending Stream that gives you the option of paying back what you owe over a longer period. You can still pay early, including in the same month, and save on interest but you have the comfort of knowing you have up to 6 months to repay. This means each payment is lower than if you had to pay it off all in one go. |
     | Payday loans, are regulated by the Financial Conduct Authority. This means there is regulation in place to make sure interest rates and fees are fair and affordable to customers.                                                                                                                                                                                                                                                                 |
     | Take a look below at our frequently asked questions on payday loans. These can answer questions if you want a payday loan for £100, £300, £500 or any other amount. They can also help you understand more about payday loans for emergencies and payday loans for bad credit.                                                                                                                                                                     |
     | FAQs                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Did you know?                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | Repay early and save                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | We know that your circumstances can change, so you can repay early at any time, and save on interest.                                                                                                                                                                                                                                                                                                                                              |
     | Get a decision in seconds                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                           |    
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                                              |


@LS @Desktop @MobileView @UI @payday-loans @Body @content 
Scenario:LS : payday-loans: Verify the title text in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/payday-loans/"
    Then user verifies 'payday-loans' URL
    Then user verify and click on 'What are alternatives to payday loans?'
    Then verify the content of 'What are alternatives to payday loans?' page
     | Alternatives to payday loans depend on what’s available to you. There may be over-the-counter lending in your area, or even pawn shops. Lending Stream offers a six-month instalment loan. We think this is a better option than having to repay your loan in one go.                                                                                                             |
    Then user verify and click on 'Do payday loans affect your credit score?'
    Then verify the content of  'Do payday loans affect your credit score?' page
     | If you accept a loan offer, that will be shown on your credit history. That’s not a bad thing or unusual! It’s exactly how credit scores and credit histories are meant to work. In fact, repaying on time (or early) could actually help your credit score. One important thing to remember is that repaying late or missing payments will also be recorded on your credit file. |
   
@LS @Desktop @MobileView @UI @payday-loans @Body @content 
Scenario:LS : payday-loans: Verify the What are the best payday loans? text in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/payday-loans/"
    Then user verifies 'payday-loans' URL
    Then user verify and click on 'What are the best payday loans?'
    Then verify the content of  'What are the best payday loans?' page 
     | content                                                                                                                                                                                                              |
     | The ‘best payday loan’ is likely to be the one that suits your needs the best. Just because one suits one person doesn’t mean it’ll suit everyone.                                                                   |
     | This is why it’s important to look carefully at your finances and what you need before applying anywhere. We’d prefer you to do your research and then apply to us because you think we’re the best option for you.  |
     | We believe we are the best option for people who want payday loans. And according to Reviews.co.uk, it seems like a lot of our customers agree.                                                                      |

@LS @Desktop @MobileView @UI @payday-loans @Body @content 
Scenario:LS : payday-loans: Verify the Can you repay payday loans early? text in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/payday-loans/"
    Then user verifies 'payday-loans' URL
    Then user verify and click on 'Can you repay payday loans early?'
    Then verify the content of  'Can you repay payday loans early?' page
     | content                                                                                                                                                                                                                                                                                                                   |
     | Here at Lending Stream, we don’t charge you any fees to repay early. Because we charge interest on a daily rate, you’ll only repay the interest up until the day you repay. This means that you could save quite a bit of cash by repaying early!                                                                         |
     | Here’s a quick example*:                                                                                                                                                                                                                                                                                                  |
     | £500 repaid over 6 months: £954.95                                                                                                                                                                                                                                                                                        |
     | £500 repaid over 3 months: £790.79                                                                                                                                                                                                                                                                                        |
     | Total saving: £164.16                                                                                                                                                                                                                                                                                                     |
     | So, if you repaid in three months instead of six, you’d only pay interest for those three months. If you’ve cut that down by repaying early, that means less interest overall.                                                                                                                                            |
     | *Because it’s a daily interest rate, these costs might be slightly different depending on how many days are in each month. Also, it might be different depending on exactly when you repay early. In this example, the customer paid two months at the planned rate, then repaid everything else on their third repayment.|

@LS @Desktop @MobileView @UI @payday-loans @Body @content 
Scenario:LS : payday-loans: Verify the Why is the APR on payday loans so high? text in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/payday-loans/"
    Then user verifies 'payday-loans' URL
    Then user verify and click on 'Why is the APR on payday loans so high?'
    Then verify the content of  'Why is the APR on payday loans so high?' page
     | content                                                                                                                                                                                                                                                                                                                                                     |
     | APR is an annual percentage rate. This means that the interest is shown as if you took out the loan for a year. It’s meant to help you to compare interest rates between long-term loans.                                                                                                                                                                   |
     | With short-term loans, it can sometimes be more complicated. If it’s a loan that’s for less than a year, the interest is shown as if it was for a full year. It also ignores anything that is repaid, which makes the interest rate look even higher. . .                                                                                                   |
     | As a result, the APR shown can seem very high. If you find APR confusing, you’re not alone. It can sometimes be difficult to understand with short-term loans. However, take a look at the actual amounts you’ll have to repay. This means looking at the monthly repayments, how many repayments you have to make, and the total amount you have to repay. |

@LS @Desktop @MobileView @UI @payday-loans @Body @link
Scenario: LS: payday-loans: Check all the links in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/payday-loans/"
    Then user verifies 'payday-loans' URL
    Then verify the links in 'payday-loans' page
     | link                                             | url                                                                          |
     | Apply Now                                        | https://preprod2-re.globalanalytics.in/application/apply/                    |
     | moneyadviceservice.org.uk                        | https://www.moneyadviceservice.org.uk/en                                     |
     | Check out our FAQs below                         | https://preprod2-re.globalanalytics.in/loans/payday-loans/#Payday-Loans-FAQs |
     | Read more about repaying early in our FAQs below | https://preprod2-re.globalanalytics.in/loans/payday-loans/#Payday-Loans-FAQs |
     | Apply Now                                        | https://preprod2-re.globalanalytics.in/application/apply/ |
     | Reviews.co.uk                                    | https://lending-stream.reviews.co.uk/                     |
     | Apply Now                                        | https://preprod2-re.globalanalytics.in/application/apply/ |
     | Apply Now                                        | https://preprod2-re.globalanalytics.in/application/apply/ |

@LS @Desktop @MobileView @UI @payday-loans @Body @slide 
Scenario: LS: payday-loans: Check the Customer Reviews in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/payday-loans/"
    Then user verifies 'payday-loans' URL
    Then verify 'What customers say' is dispalyed
    Then verify  content of slides
     |Slide Content                                                                                              |
     |"I love this company. They have always been there when I have needed them. Would highly recommend them"    |
     |Tania, 14th January 2020                                                                                   |
     |"I would recommend lending stream to friends and family.Thank you."                                        |
     |keely, 16th January 2020                                                                                   |                                 
     |"Thanks Lending Stream for helping me. Quick and easy application process."                                |
     |Gavin, 20th January 2020                                                                                   |
   