Feature: Lending stream compare-loans pounds-to-pocket page test plan

@LS @Desktop @MobileView @UI @compare-loans @pounds-to-pocket @Body @content 
Scenario: LS: pounds-to-pocket: Verify the body content in pounds-to-pocket page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/pounds-to-pocket/"
    Then user verifies 'pounds-to-pocket' URL
    Then verifies content of 'pounds-to-pocket' 
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | Looking for Pounds to Pocket Loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | As Pounds to Pocket is no longer lending​​​​​​                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | If you’re in need of extra cash and you were planning to take out a loan with Pounds to Pocket, you may be unsure what to do now that they are no longer lending. But Lending Stream is open for business, so you can apply for a six-month loan right now.                                                                                                                                                                                                                              |
     | Pounds to Pocket loans used to offer loans for between six to twelve months. However, as with their sister brand, QuickQuid, they were operated by CashEuroNet UK LLC, which has now gone into administration.                                                                                                                                                                                                                                                                           |
     | It also might be useful to know how fast Lending Stream is. While Pounds to Pocket used to specify that it could take up to 30 minutes for the approval process to go through (and then up to a further 10 minutes for the cash to be transferred), Lending Stream offers fast decisions. And if you’re approved, we’ll send the cash to your bank in under 90 seconds.                                                                                                                  |
     | A different lender to Pounds to Pocket                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | Lending Stream offers loans in a different way to how Pounds to Pocket used to. At Lending Stream, we pride ourselves on putting the customer first. And that means quick decisions. We understand that speed is of the essence when you need quick loans. So we use sophisticated online algorithms to analyse your application and come back with a quick but affordable, responsible lending decision. So you don't need to wait around to be contacted - you'll get a fast decision. |
     | We also understand that you might want to make extra payments in your own time depending on your financial circumstances, so we make it easy to have alternatives to direct debits or continuous payment authorities. At any time, you can log into your online account and make an extra payment in your own time. No need to wait to deal with anyone - it's all in your control.                                                                                                      |
     | Other options                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
     | If you're looking for a six month loan, and have used Pounds to Pocket before, then you may find that Lending Stream fulfils your needs. All you have to do is apply online and you'll get a quick decision. And if your loan is agreed, we'll send the cash to your bank in under 90 seconds.                                                                                                                                                                                           |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                                            |
     | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Online applications                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | Apply online anytime - no need to visit a store.                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | Faster money transfer                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | We can send cash to your bank within 90 seconds of your loan being confirmed.                                                                                                                                                                                                                                                                                                                                                                                                            |
     | No hidden fees                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | We don't charge an application fee or transfer fee.                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                                                                                    |

@LS @Desktop @MobileView @UI @compare-loans @pounds-to-pocket @Body @slide 
Scenario: LS: pounds-to-pocket: Verify the Customer Reviews in pounds-to-pocket page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/pounds-to-pocket/"
    Then user verifies 'pounds-to-pocket' URL
    Then verify 'Read Our Reviews' heading 
    Then verify  content of slides
     |Slides Content                                                                                             |
     |"I love this company. They have always been there when I have needed them. Would highly recommend them"    |
     |Tania, 14th January 2020                                                                                   |
     |"I would recommend lending stream to friends and family.Thank you."                                        |
     |keely, 16th January 2020                                                                                   |                                 
     |"Thanks Lending Stream for helping me. Quick and easy application process."                                |
     |Gavin, 20th January 2020                                                                                   |

@LS @Desktop @MobileView @UI @compare-loans @pounds-to-pocket @Body @link
Scenario: LS: pounds-to-pocket: Verify all the links in pounds-to-pocket page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/pounds-to-pocket/"
    Then user verifies 'pounds-to-pocket' URL
    Then verify the links in 'pounds-to-pocket' page
     | link                       | url                                                                     |
     | Home                       | https://preprod2-re.globalanalytics.in/                                 |
     | Compare Loans              | https://preprod2-re.globalanalytics.in/compare-loans/                   |
     | Pounds To Pocket           | https://preprod2-re.globalanalytics.in/compare-loans/pounds-to-pocket/  |
     | QuickQuid                  | https://preprod2-re.globalanalytics.in/compare-loans/quickquid/         |
     | quick loans                | https://preprod2-re.globalanalytics.in/loans/quick-loans/               |
     | Apply Now                  | https://preprod2-re.globalanalytics.in/application/apply/               |
     | moneyadviceservice.org.uk  | https://www.moneyadviceservice.org.uk/en                                |
     | Read more reviews          | https://lending-stream.reviews.co.uk/                                   |

