Feature: Lending stream compare-loans satsuma page test plan

@LS @Desktop @MobileView @UI @compare-loans @satsuma @Body @content
Scenario: LS: Satsuma: Verify the static content in satsuma page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/satsuma/"
    Then user verifies 'compare-loans-satsuma' URL
    Then verify content of 'compare-loans-satsuma' page
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | Looking for Satsuma Loans? Read this first.                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | Satsuma Loans aren’t lending right now. We are, though.                                                                                                                                                                                                                                                                                                                                                                                                             |
     | Satsuma Loans aren’t currently lending. So if you’ve taken a loan out with them before, and are looking to do so again, you might be feeling a bit short-changed. You can still apply with Lending Stream right now, though. And judging by our better review scores, you might prefer it.                                                                                                                                                                          |
     | About Satsuma Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Satsuma Loans are relatively short-term loans, which you can apply for online. With a Satsuma Loan, you can apply for up to £1,000 as a first time customer, which you can borrow over weekly or monthly repayments for up to a year.                                                                                                                                                                                                                               |
     | If you're approved, it'll take up to an hour to get the money in your account, most of the time. However, if you apply after 11pm, they won't promise hourly payments until the next morning.                                                                                                                                                                                                                                                                       |
     | With Lending Stream, we offer 6 month loans, up to £1,500. Oh, and if you’re approved we’ll send the cash to your bank in 90 seconds. No need to wait until the next morning.                                                                                                                                                                                                                                                                                       |
     | Can I repay early?                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | You can, but it seems to be more complicated with Satsuma. According to their website, you have to contact them to request a loan settlement amount. At that point, they’ll tell you how much you have to repay. We prefer to have that information available for you in your online account. Just log in to see how much you have left to repay. If you want to make an extra repayment, or repay the entire amount, you can do that on your account section too.  |
     | With both Satsuma and Lending Stream, interest is charged on a daily basis. This means that you could save money if you repay early!                                                                                                                                                                                                                                                                                                                                |
     | What types of loans do Satsuma offer?                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Satsuma offer loans for up to a year, with either monthly or weekly repayments. At Lending Stream, we offer six-month loans. You can make payments monthly or weekly as well (but don’t forget, you can also repay early and save money on interest).                                                                                                                                                                                                               |
     | How fast are Satsuma loans?                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | If you’re approved by Satsuma, they’ll send the cash to your bank within an hour, as long as it’s between 6am and 11pm. If you’re outside of those hours, you’ll need to wait for the next day.                                                                                                                                                                                                                                                                     |
     | At Lending Stream, we’re much faster. We’ll send the cash to your bank in just 90 seconds. And it doesn’t matter whether it’s day or night.                                                                                                                                                                                                                                                                                                                         |
     | What’s the minimum and maximum amount for a Satsuma Loan?                                                                                                                                                                                                                                                                                                                                                                                                           |
     | The minimum amount Satsuma offers is £100. The minimum amount that Lending Stream offers is £50.                                                                                                                                                                                                                                                                                                                                                                    |
     | The maximum Satsuma offers is £2,000 if you’ve used them before. If you’ve used Lending Stream before, you can apply for up to £1,500.                                                                                                                                                                                                                                                                                                                              |
     | What is Satsuma’s APR?                                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | Satsuma shows a representative APR of 535% on their homepage, but elsewhere they mention that the APR can go as high as 1575%. This is because of the different times people can borrow for. Their representative APR is based on a 9 month loan, not a 6 month loan.                                                                                                                                                                                               |
     | It’s worth looking at the actual cost. In our representative example, we show how £200 borrowed over 6 months would mean repaying a total of £386.61. According to Satsuma’s loan calculator, borrowing £200 for 6 months with them would mean repaying £379.20 (and £382.98 if you repay weekly).                                                                                                                                                                  |
     | That’s a lot closer in real money than the APR might make it look at first, especially over 6 months. So it’s always worth looking at exactly what you’re likely to repay.                                                                                                                                                                                                                                                                                          |
     | About Satsuma Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Satsuma short-term loans are also a sister-brand to Vanquis credit cards, which are credit cards aimed at people with lower credit records. In a similar way to Vanquis being marketed as credit builder cards, some see Satsuma as bad credit loans - however, as with any loan, if you don’t repay on time, it could make your credit score worse.                                                                                                                |
     | Are Lending Stream loans faster than Satsuma Loans?                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | If you don't have time to wait around for an hour, you might want to try Lending Stream quick loans. We'll give you a near-instant decision. If you’re approved, we’ll send the cash to your bank in under 90 seconds.                                                                                                                                                                                                                                              |
     | Also, we make it easier for you to be in control of your loan. If you want to repay early, you can do that at any time from your account online. With Satsuma, you need to call them to make further (or early) payments and get a quote on the outstanding amount.                                                                                                                                                                                                 |
     | We prefer to give you options. That's why we make it easy for you to repay your loan early if you want. If you'd rather we take the payment using continuous payment authority, we can do that too, so you never have to think about it. But we figured 'what's the point in having an online account and app if you can't make payments through it whenever suits you best?'                                                                                       |
     | Do I need to send in paperwork?                                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | Sending in paperwork, even by email, can take time. If your application needs more evidence, then Satsuma ask you to gather paperwork and send it to them, at which point, they’ll process within two working days (but not bank holidays or weekends).                                                                                                                                                                                                             |
     | At Lending Stream, we understand that you may still need fast access to cash in an emergency. So we use open banking technology to allow us to make a quick decision. Rather than sending in paperwork, we ask you to let us see some of your bank transactions in a secure way. This will be a lot quicker than printing and sending paperwork!                                                                                                                    |
     | Loans like Satsuma                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | Are you looking for a Satsuma loan? If so, then before you apply, why not try Lending Stream first? You might find that the options we offer (like 24hr loan payouts and early repayments without having to deal with a customer representative) suit you better. Lending Stream offers a longer-term alternative to payday loans.                                                                                                                                  |
     | Why not find out more?                                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                            |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                       |
     | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Online applications                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Apply online anytime - no need to visit a store.                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Faster money transfer                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | We can send cash to your bank within 90 seconds of your loan being confirmed.                                                                                                                                                                                                                                                                                                                                                                                       |
     | No hidden fees                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | We don't charge an application fee or transfer fee.                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                                                               |

@LS @Desktop @MobileView @UI @compare-loans @satsuma @Body @table
Scenario: LS: Satsuma: Check the table content in satsuma page
   Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/satsuma/"
   Then user verifies 'compare-loans-satsuma' URL
   Then verify 'Representative example' heading is present
   Then verify content of Representative example table
      | left_value             | right_value |
      | Annual Interest Rate   | 292.0%      |
      | Total amount of credit | £200        |
      | Representative APR     | 1333%       |
      | Duration of agreement  | 6 months    |
      | Total amount payable   | £386.61     |
      | Total charge of credit | £186.61     |
      | Six repayments of:     | £64.44      |

@LS @Desktop @MobileView @UI @compare-loans @satsuma @Body @slide
Scenario: LS: Satsuma: Verify the Customer Reviews in satsuma page
   Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/satsuma/"
   Then user verifies 'compare-loans-satsuma' URL
   Then verify 'Read Our Reviews' heading 
   Then verify  content of slides
     |Slides Content                                                                                             |
     |"I love this company. They have always been there when I have needed them. Would highly recommend them"    |
     |Tania, 14th January 2020                                                                                   |
     |"I would recommend lending stream to friends and family.Thank you."                                        |
     |keely, 16th January 2020                                                                                   |                                 
     |"Thanks Lending Stream for helping me. Quick and easy application process."                                |
     |Gavin, 20th January 2020                                                                                   |

@LS @Desktop @MobileView @UI @compare-loans @satsuma @Body @link 
Scenario: LS: Satsuma: Check the links in satsuma page
   Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/satsuma/"
   Then user verifies 'compare-loans-satsuma' URL
   Then verify links of 'compare-loans-satsuma' page
     | link                             | url                                                            |
     | Home                             | https://preprod2-re.globalanalytics.in/                        |
     | Compare Loans                    | https://preprod2-re.globalanalytics.in/compare-loans/          |
     | Satsuma Loans                    | https://preprod2-re.globalanalytics.in/compare-loans/satsuma/  |
     | short-term loans                 | https://preprod2-re.globalanalytics.in/loans/short-term-loans  |
     | bad credit loans                 | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/ |
     | quick loans                      | https://preprod2-re.globalanalytics.in/loans/quick-loans/      |
     | payday loans                     | https://preprod2-re.globalanalytics.in/loans/payday-loans/     | 
     | Apply Now                        | https://preprod2-re.globalanalytics.in/application/apply/      |
     | moneyadviceservice.org.uk        | https://www.moneyadviceservice.org.uk/en                       |
     | Read more reviews                | https://lending-stream.reviews.co.uk/                          |
