Feature: Lending stream short-term-loans page test plan

@LS @Desktop @MobileView @UI @short-term-loans @Body @content 
Scenario: LS: short-term-loans: Verify the body content in short-term-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/short-term-loans/"
    Then user verifies 'short-term-loans' URL
    Then verify the content of 'short-term-loans' page
     | content                                                                                                                                                                                                                                                                                                                                               |
     | ✓ Quick application       ✓ Fast cash transfer                                                                                                                                                                                                                                                                                                       |
     | Short-Term Loans from                                                                                                                                                                                                                                                                                                                                 |
     | Lending Stream                                                                                                                                                                                                                                                                                                                                        |
     | Up to £1500 to your bank in 90 seconds if approved                                                                                                                                                                                                                                                                                                    |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                              |
     | Warning: Late repayment can cause you serious money problems. For help go to moneyadviceservice.org.uk                                                                                                                                                                                                                                                |
     | Looking for a short-term loan?                                                                                                                                                                                                                                                                                                                        |
     | If you’re approved by Lending Stream, we’ll send your short-term loan straight to your bank in 90 seconds.                                                                                                                                                                                                                                            |
     | Sometimes, emergencies happen that mean you need some short-term cash in a hurry. When that happens, you want to know you’re dealing with a responsible lender, but you also don’t want to wait around. This is why we use clever technology to help us make appropriate decisions quickly.                                                           |
     | Short-term loans from a direct lender                                                                                                                                                                                                                                                                                                                 |
     | When you search for short-term loans, the amount of choice can seem overwhelming. But it’s worth looking at any options carefully before you apply. In particular, applying with a short-term loans direct lender can be a more transparent and straightforward way to do it.                                                                         |
     | Lending Stream is a direct lender for short-term loans. If you apply with us, we’ll give you a straightforward, near-instant decision. And if we need more information, we can do that online quickly without you having to send us any extra paperwork.                                                                                              |
     | Six-month short-term loans                                                                                                                                                                                                                                                                                                                            |
     | With Lending Stream, you’ll get six months to repay your short-term loan. And we won’t keep you waiting around either! Just fill in our online application form and, if approved, we’ll send the cash to your bank in under 90 seconds.                                                                                                               |
     | If you want to repay your loan sooner than six months, that’s fine too! You can repay as early as you want with no extra fees. And because our loans are charged at a daily interest rate, you’ll save money if you repay early. In fact, most of our customers repay their loan in 3-4 months.                                                       |
     | Here’s a quick example:                                                                                                                                                                                                                                                                                                                               |
     | £500 repaid over 6 months: £954.95                                                                                                                                                                                                                                                                                                                    |
     | £500 repaid over 3 months: £790.79                                                                                                                                                                                                                                                                                                                    |
     | Total saving: £164.16                                                                                                                                                                                                                                                                                                                                 |
     | Interest is based on the amount you have left to repay, and how long you borrow it for. So, if you repaid in 3 months instead of 6, you’d only pay interest for those 3 months. will mean paying less interest. And don’t worry – there are no early repayment fees.                                                                                  |
     | *The number of days in the month might affect the exact repayment amounts. Also, it might depend on how much you repay and when. In the above example, the customer repaid the outstanding amount on the third month.                                                                                                                                 |
     | To apply, just fill in our quick application form online.​​​​​​                                                                                                                                                                                                                                                                                             |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                              |
     | Warning: Late repayment can cause you serious money problems. For help go to moneyadviceservice.org.uk                                                                                                                                                                                                                                                |
     | Why Lending Stream?                                                                                                                                                                                                                                                                                                                                   |
     | Fast                                                                                                                                                                                                                                                                                                                                                  |
     | Cash to your bank in under 90 seconds                                                                                                                                                                                                                                                                                                                 |
     | Convenient                                                                                                                                                                                                                                                                                                                                            |
     | Secure application and fast decision                                                                                                                                                                                                                                                                                                                  |
     | Affordable                                                                                                                                                                                                                                                                                                                                            |
     | Six months to repay                                                                                                                                                                                                                                                                                                                                   |
     | Trusted                                                                                                                                                                                                                                                                                                                                               |
     | High rating on Reviews.co.uk                                                                                                                                                                                                                                                                                                                          |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                              |
     | FAQs                                                                                                                                                                                                                                                                                                                                                  |
     | Did you know?                                                                                                                                                                                                                                                                                                                                         |
     | Repay early and save                                                                                                                                                                                                                                                                                                                                  |
     | You can repay early at any time, with no extra fees. In fact, you’ll save money because there’ll be less interest to pay. We encourage this, in fact – most of our customers repay early and save cash.                                                                                                                                               |
     | Get a decision in seconds                                                                                                                                                                                                                                                                                                                             |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                              |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees. |


@LS @Desktop @MobileView @UI @short-term-loans @Body @content 
Scenario: LS: short-term-loans: Verify the FAQ content in short-term-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/short-term-loans/"
    Then user verifies 'short-term-loans' URL
    Then user verify and click on 'What are short-term loans?'
    Then verify the content of 'What are short-term loans?'
     | Short-term loans are usually loans that are repaid in a year or less. Loans under three months tend to be referred to as ‘payday loans’. You can apply for short-term loans online, and you get a decision in anything from a few minutes to a few days (depending on the lender). At Lending Stream, we usually make decisions in seconds.                                                                                                                                                                                    |
    Then user verify and click on 'Will short-term loans affect my credit score?'
    Then verify the content of  'Will short-term loans affect my credit score?'
    | Using any type of credit will affect your credit score, either in a good way or a bad way. Taking out a short-term loan will affect your credit file, which may change your credit score. Any new loan will usually cause your credit score to go down a bit (as you’re using more available credit). Making repayments on time will show up as a positive on your credit file though, which can help your credit score to go up. This isn’t unusual for short-term loans. This is exactly how credit scores are meant to work. |

 @LS @Desktop @MobileView @UI @short-term-loans @Body @content 
 Scenario: LS: short-term-loans: Verify the "Is it possible to get short-term loans for bad credit?" content in short-term-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/short-term-loans/"
    Then user verifies 'short-term-loans' URL
    Then user verify and click on 'Is it possible to get short-term loans for bad credit?'
    Then verify the content of  'Is it possible to get short-term loans for bad credit?'
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | If you’re looking for short-term loans, bad credit might not be a barrier. We’ll look at your overall affordability as well as your credit history. We understand that you might have bad credit while being able to afford a short-term loan.                                                                                                                                                                                                                                        |
     | In some cases, we might need to take a look at some more of your current finances, to make sure you can afford a loan. Some other lenders need you to send paperwork to them when this happens. We’ve gone with a much faster method that’s still secure. We use Open Banking to help us make the decision while keeping your personal information safe. This helps us make really fast and accurate lending decisions, based on your most up to date income and expenditure details. |

@LS @Desktop @MobileView @UI @short-term-loans @Body @content 
Scenario: LS: short-term-loans: Verify the "How do short-term loans work?" content in short-term-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/short-term-loans/"
    Then user verifies 'short-term-loans' URL
    Then user verify and click on 'How do short-term loans work?'
    Then verify the content of  'How do short-term loans work?'
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Short-term loans can vary from lender to lender. Some might offer loans for just a month or two (commonly referred to as ‘payday loans’). Other lenders might offer loans for 6 or 12 months. Usually, a payment schedule will be set up, with weekly or monthly repayments.                                                                                                                                                                                     |
     | Short-term loans from Lending Stream are for six months, but you can repay earlier if you’d like (and you’ll even save cash). The process is straightforward - you just apply online and, if approved, the cash is transferred to your bank in under 90 seconds. You then pay it back with monthly repayments – these can either be automated or you can make your own payments. At any point, you can repay extra using your debit card. More about repayments. |

@LS @Desktop @MobileView @UI @short-term-loans @Body @content 
Scenario: LS: short-term-loans: Verify the "How do short-term loans work?" content in short-term-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/short-term-loans/"
    Then user verifies 'short-term-loans' URL
    Then user verify and click on 'How do short-term loans work?'
    Then verify the links of  'How do short-term loans work?'
     | link                        | url                                                        |
     | ‘payday loans’              | https://preprod2-re.globalanalytics.in/loans/payday-loans/ |
     | More about repayments       | https://preprod2-re.globalanalytics.in/faqs/               |

@LS @Desktop @MobileView @UI @short-term-loans @Body @link 
Scenario: LS: short-term-loans: Verify the "How do short-term loans work?" link in short-term-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/short-term-loans/"
    Then user verifies 'short-term-loans' URL
    Then verify the links on 'short-term-loans' page
     | title                            | link                        | url                                                                          |
     | Short Term Loans Direct Lenders  | Apply Now                   | https://preprod2-re.globalanalytics.in/application/apply/                    |
     | Short Term Loans Direct Lenders  | moneyadviceservice.org.uk   | https://www.moneyadviceservice.org.uk/en                                     |
     | Six-month short-term loans       | Apply Now                   | https://preprod2-re.globalanalytics.in/application/apply/                    |
     | Six-month short-term loans       | moneyadviceservice.org.uk   | https://www.moneyadviceservice.org.uk/en                                     |
     | Why Lending Stream?              | Reviews.co.uk               | https://lending-stream.reviews.co.uk/                                        |
     | Why Lending Stream?              | Apply Now                   | https://preprod2-re.globalanalytics.in/application/apply/                    |
     | Did you know?                    | Apply Now                   | https://preprod2-re.globalanalytics.in/application/apply/                    |

@LS @Desktop @MobileView @UI @payday-loans @Body @slide 
Scenario: LS: payday-loans: Check the Customer Reviews in payday-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/short-term-loans/"
    Then user verifies 'short-term-loans' URL
    Then verify 'What customers say' is dispalyed
    Then verify  content of slides
     |Slide Content                                                                                              |
     |"I love this company. They have always been there when I have needed them. Would highly recommend them"    |
     |Tania, 14th January 2020                                                                                   |
     |"I would recommend lending stream to friends and family.Thank you."                                        |
     |keely, 16th January 2020                                                                                   |                                 
     |"Thanks Lending Stream for helping me. Quick and easy application process."                                |
     |Gavin, 20th January 2020                                                                                   |
   