Feature: Lending stream compare-loans sunny page test plan

 @LS @Desktop @MobileView @UI @compare-loans @sunny @Body @content 
 Scenario: LS: sunny: Verify the body content in sunny page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/sunny/"
    Then user verifies 'compare-loans-sunny' URL
    Then verfiy the content of 'compare-loans-sunny' page
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Can't get Sunny Loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | Are you a Sunny customer, but found that they’re no longer lending? If so, you might want to try Lending Stream. We think we’ll offer you great service that you won't get elsewhere.                                                                                                                                                                                                                                                                                                                   |
     | Oh, and we're faster than Sunny were.                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | And we charge the same maximum daily rate as a Sunny loan                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | (0.8% per day).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | Lending Stream – open for lending                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
     | You can apply with Lending Stream any time, 24/7.                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | ​​​​​​For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | But if you want to find out more, that's fine too.                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | How much could you apply for with Sunny?                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | It depends how long you wanted to borrow for. Sunny offered loans for up to £2,500, but that was for over a year. According to their site, you could apply for up to £1,000 for 6 months. With lending Stream, you can apply for up to £1,500 for 6 months.                                                                                                                                                                                                                                             |
     | How long did it take to get the cash with Sunny?                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
     | Sunny said they’d get the cash to you in 15 minutes, as long as your application was approved. We won’t lie – that’s pretty fast. But we’re faster. If you’re approved, we’ll send the cash to your bank in 90 seconds.                                                                                                                                                                                                                                                                                 |
     | Now that’s fast.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | ​​​​​​For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | How fast is it to find out if you’ll be accepted?                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
     | Assuming they didn’t need to see any verification of your information, Sunny claimed to give you an instant decision. However, if they needed to verify anything, they’d email you and let you know how to upload documents for them to check.                                                                                                                                                                                                                                                          |
     | We have a faster method. We use open banking, which lets us securely check the information we need from your bank account. It’s amazingly fast compared to scanning and sending documents. In most cases, we make near-instant lending decisions too.                                                                                                                                                                                                                                                   |
     | What was the Daily interest rate for Sunny?                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | Sunny charged the same daily rate as Lending Stream. That’s 0.8% a day. You can find out more about our loans in our FAQS                                                                                                                                                                                                                                                                                                                                                                               |
     | What was Sunny’s representative APR?                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Sunny’s representative APR was 1267%. That’s a little lower than Lending Stream, at 1333%, even though we charge the same daily rate.                                                                                                                                                                                                                                                                                                                                                                   |
     | Oddly enough, on their website, Sunny stated that borrowing £100 for 6 months is £197.82. Despite the lower APR, borrowing the same amount from Lending Stream will cost £190.99. which is, erm… less.                                                                                                                                                                                                                                                                                                  |
     | Because of the daily interest rate, it might be that they calculated using six months with more days in them than we have. However they got there, it makes one thing clear – it’s worth finding out exactly how much you’ll be expected to repay before you apply. Representative APRs are useful, but they’re not always the easiest way to compare loans.                                                                                                                                            |
     | Did Sunny offer loans for bad credit?                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | If you had bad credit and were looking for a loan, Sunny may have been able to help you. Just like Lending Stream, Sunny took a look at your current finances to help decide if you could afford the loan you want. Credit scores are also part of it, but they’re not the only thing. At Lending Stream, we look at more.                                                                                                                                                                              |
     | If you do take out a loan, it will show up on your credit record. Repaying it on time may even help improve your credit score.                                                                                                                                                                                                                                                                                                                                                                          |
     | How Sunny loans worked                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | When you applied with Sunny, you filled in an online application form. You could apply to borrow money which you repaid with monthly instalments. You could borrow for as little as 6 months to as many as 14 months, as a longer-term alternative to payday loans.                                                                                                                                                                                                                                     |
     | The representative APR changed, depending how long you took out the loan for (it's lower for longer loans - if you're not sure why this is, find out about APR). Just because you applied for a Sunny loan with a lower representative APR didn't mean you'd always get that rate if you were approved - all applications were subject to a credit check. You may have received a higher rate if you were looking for a bad credit loan, when your credit history wasn't as strong as other applicants. |
     | How Lending Stream quick loans work                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | We only offer six-month loans. If you apply and are approved, you'll get a loan that you repay over six months. You'll get a quick decision and we'll send the cash to your bank in under 90 seconds.                                                                                                                                                                                                                                                                                                   |
     | And if you want to repay earlier, that's fine. We won't charge you any extra for that and it's easy to do. You can find out more about how Lending Stream works here.                                                                                                                                                                                                                                                                                                                                   |
     | Loans like Sunny                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
     | Are you in need of some cash and looking at a six month loan, but aren’t sure what to do now Sunny have stopped lending? It might be worth looking at Lending Stream. We offer a flexible approach to lending, since you can take as much control over repayments as you want.                                                                                                                                                                                                                          |
     | Used us before? If so, then you can also apply for more over six months with Lending Stream than you could with Sunny Loans. In fact, you can apply for up to £1,500, instead of Sunny's £1,000.                                                                                                                                                                                                                                                                                                        |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | ​​​​​​For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | Online applications                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | Apply online anytime - no need to visit a store.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
     | Faster money transfer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | We can send cash to your bank within 90 seconds of your loan being confirmed.                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | No hidden fees                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | We don't charge an application fee or transfer fee.                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                                                                                                   |
 
@LS @Desktop @MobileView @UI @compare-loans @sunny @Body @slide 
Scenario: LS: sunny: Check the Customer Reviews slides content in sunny page   
    Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/sunny/"
    Then user verifies 'compare-loans-sunny' URL
    Then verify 'Read Our Reviews' heading 
    Then verify  content of slides
     |Slides Content                                                                                             |
     |"I love this company. They have always been there when I have needed them. Would highly recommend them"    |
     |Tania, 14th January 2020                                                                                   |
     |"I would recommend lending stream to friends and family.Thank you."                                        |
     |keely, 16th January 2020                                                                                   |                                 
     |"Thanks Lending Stream for helping me. Quick and easy application process."                                |
     |Gavin, 20th January 2020                                                                                   |
   
@LS @Desktop @MobileView @UI @compare-loans @sunny @Body @link 
Scenario: LS: sunny: Check all the links in the sunny page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/compare-loans/sunny/"
    Then user verifies 'compare-loans-sunny' URL
    Then verify the links of 'compare-loans-sunny' page
     | link                           | url                                                             |
     | Home                           | https://preprod2-re.globalanalytics.in/                         |
     | Compare Loans                  | https://preprod2-re.globalanalytics.in/compare-loans/           |
     | Sunny Loans                    | https://preprod2-re.globalanalytics.in/compare-loans/sunny/     |
     | Apply Now                      | https://preprod2-re.globalanalytics.in/application/apply        |
     | moneyadviceservice.org.uk      | https://www.moneyadviceservice.org.uk/en                        |
     | Apply Now                      | https://preprod2-re.globalanalytics.in/application/apply/       |
     | moneyadviceservice.org.uk      | https://www.moneyadviceservice.org.uk/en                        |
     | FAQS                           | https://preprod2-re.globalanalytics.in/faqs/                    |
     | payday loans.                  | https://preprod2-re.globalanalytics.in/loans/payday-loans/      |
     | find out about APR             | https://preprod2-re.globalanalytics.in/apr-explained/           |
     | bad credit loan                | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/  |
     | how Lending Stream works here  | https://preprod2-re.globalanalytics.in/how-it-works/            |
     | Apply Now                      | https://preprod2-re.globalanalytics.in/application/apply/       |
     | moneyadviceservice.org.uk      | https://www.moneyadviceservice.org.uk/en                        |
     | Read more reviews              | https://lending-stream.reviews.co.uk/                           |
