Feature: Footer verification on all static pages

    @Footer @LS @Desktop @UI @Signin @MobileView
    Scenario Outline: LS: Desktop : MobileView : Footer: Verify H3 tag footer contents
        Given I want to open the "<URL>" page
        When I Scroll to botton of the screen
        Then I want to a take screenshot
        Then I Verify the footer content as "<Content>" on tag with "h3"

        Examples:
            | URL                                                                    | Content   |
            | https://preprod2-re.globalanalytics.in                                 | RESOURCES |
            | https://preprod2-re.globalanalytics.in                                 | COMPANY   |
            | https://preprod2-re.globalanalytics.in                                 | LEGAL     |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | RESOURCES |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | COMPANY   |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | LEGAL     |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | RESOURCES |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | COMPANY   |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | LEGAL     |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | RESOURCES |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | COMPANY   |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | LEGAL     |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | RESOURCES |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | COMPANY   |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | LEGAL     |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | RESOURCES |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | COMPANY   |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | LEGAL     |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | RESOURCES |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | COMPANY   |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | LEGAL     |
            | https://preprod2-re.globalanalytics.in/about-us/                       | RESOURCES |
            | https://preprod2-re.globalanalytics.in/about-us/                       | COMPANY   |
            | https://preprod2-re.globalanalytics.in/about-us/                       | LEGAL     |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | RESOURCES |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | COMPANY   |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | LEGAL     |
            | https://preprod2-re.globalanalytics.in/debt-management/                | RESOURCES |
            | https://preprod2-re.globalanalytics.in/debt-management/                | COMPANY   |
            | https://preprod2-re.globalanalytics.in/debt-management/                | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/                           | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/                           | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/                           | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | LEGAL     |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | RESOURCES |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | COMPANY   |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | LEGAL     |


    @Footer @LS @Desktop @UI @Signin @MobileView
    Scenario Outline: LS: Desktop : MobileView : Footer: Verify H3 tag footer contents
        Given I want to open the "<URL>" page
        When I Scroll to botton of the screen
        Then I want to a take screenshot
        Then I Verify the footer content as "<Content>" on tag with "p"

        Examples:
            | URL                                                                    | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | https://preprod2-re.globalanalytics.in                                 | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in                                 | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in                                 | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/about-us/                       | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/debt-management/                | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/                           | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/                           | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/                           | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | *Subject to loan approval, you will receive cash through our Express Cash Transfer option for free if supported by your bank. We can send cash to your bank in under 90 seconds of your loan being agreed, subject to an assessment of affordability and credit worthiness. The time that it takes for cash to appear in your account will depend on your bank's policies and procedures.#Call charges apply. Standard charges from BT landlines, mobiles and other providers may vary. |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short term financial needs but which is not appropriate for longer term borrowing or if you are in financial difficulty. All loan applications are subject to status, terms and conditions and to satisfactory passage of checks on credit worthiness and affordability.                     |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Lending Stream is a trading name of GAIN Credit LLC Contact Address: Lending Stream, Wisteria Grange Barn, Pikes End, Pinner, London, United Kingdom, HA5 2EX $pipeSymbol$ Registered Address: 251 Little Falls Drive, Wilmington, DE 19808, USA.$pipeSymbol$ Registered in the State of Delaware,USA $pipeSymbol$ Registration Number: 4124111. Authorised and Regulated by the Financial Conduct Authority. Registration Number 689378.                                               |


    @Footer @LS @Desktop @UI @Signin
    Scenario Outline: LS: Desktop: Footer: Click All links in the footer opens in new tab
        Given I want to open the "<URL>" page
        When I Scroll to botton of the screen
        Then I want to a take screenshot
        Then I Clicked on the footer "<Link>"
        Then I want to a take screenshot
        Then I want to switch to the URL as "<NewURL>"
        Then I want to verify the URL as "<NewURL>"
        Then I Closes rest of the tabs

        Examples:
            | URL                                                                    | Link             | NewURL                                                         |
            | https://preprod2-re.globalanalytics.in                                 | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in                                 | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in                                 | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in                                 | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in                                 | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in                                 | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in                                 | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in                                 | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in                                 | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in                                 | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in                                 | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/         | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/loans/quick-loans/              | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/           | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/loans/3-month-loans/            | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/          | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/compare-payday-loans/           | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/about-us/                       | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/about-us/                       | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/about-us/                       | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/about-us/                       | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/about-us/                       | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/apr-explained/                  | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/debt-management/                | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/debt-management/                | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/debt-management/                | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/debt-management/                | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/debt-management/                | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/additional-loan/           | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/borrowing-limits/          | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/complaints/                | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/contact-us/                | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/guarantee-loan-approval/   | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-approval/             | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-eligibility/          | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                 | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-not-approved/         | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/loan-streaming-in-minutes/ | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/representative-example/    | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | FAQs             | https://preprod2-re.globalanalytics.in/faqs/                   |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Contact          | https://preprod2-re.globalanalytics.in/contactus/              |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | File a complaint | https://preprod2-re.globalanalytics.in/contactus/#complaint    |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Leave a review   | https://preprod2-re.globalanalytics.in/contactus/#feedback     |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Blog             | https://preprod2-re.globalanalytics.in/blog/                   |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | About Us         | https://preprod2-re.globalanalytics.in/about-us/               |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | How it Works     | https://preprod2-re.globalanalytics.in/how-it-works/           |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Sitemap          | https://preprod2-re.globalanalytics.in/sitemap/                |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Terms of Use     | https://preprod2-re.globalanalytics.in/legal/terms-of-use/     |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Privacy Policy   | https://preprod2-re.globalanalytics.in/legal/privacy-policy/   |
            | https://preprod2-re.globalanalytics.in/faqs/total-repayment-amount/    | Fraud Disclaimer | https://preprod2-re.globalanalytics.in/legal/fraud-disclaimer/ |
