Feature:verify content in 3 Month Loans page content and Links

@LS @Loans_Page @3_Month_Loans @UI @Desktop @MobileView @Body @content
Scenario:LS: Loans: Verify the page content of 3_Month_Loans
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/3-month-loans/"
    Then user verifies '3_month_loans' URL
    Then verify the content of '3_month_loans' page
        | Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
        | 3 month loans: What you need to know                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
        | What are 3 month loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
        | As the name suggests, 3 month loans are short-term loans that you repay over three months. They're usually for fairly small amounts of money (for hundreds rather than thousands of pounds) and usually designed for either emergencies or to help with a short gap in the borrower's finances.                                                                                                                                                                                                                                                                                  |
        | Lending Stream and 3 month loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
        | We offer six month loans, as we believe it's better to spread out payments over a slightly longer period. If you're repaying in three months, that can mean more expensive monthly repayments.                                                                                                                                                                                                                                                                                                                                                                                   |
        | However, if you want to, you can repay early with Lending Stream. There's absolutely no penalty for doing so and you can save on interest as a result - so if you want to repay in three months, you can do. So before you apply for a 3 month loan online, check out our 6 month loans and see if it might make more sense for you.                                                                                                                                                                                                                                             |
        | Apply Now                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
        | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
        | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
        | Are 3 month loans the same as payday loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
        | Although there isn't a precise definition, 3 month loans can be a type of payday loan. While more traditional payday loans tend to be for a month or so, most payday lenders now offer borrowers the ability to repay over multiple instalments over a short period of time.                                                                                                                                                                                                                                                                                                     |
        | They've become more popular in recent years, as online payday lenders have started offering more options for borrowing and many have started advertising three month payday loans. Payday loans started off as deferred-payment loans, where you could use post-dated cheques to borrow money (with the cheques post-dated until you got paid). With the rise of digital lenders and debit cards, borrowers have been offered more options and short instalment loans have become more popular. This has led to more 3 month loan direct lenders being available.                |
        | 3 month loans can sometimes have a lower representative APR than one-month payday loans, even if you repay the same amount overall. This is because of how the representative APR is calculated - it's an annual rate, so the interest it shows is multiplied and compounded (which is when the amount is added onto the total before being multiplied again) until it shows the amount you would repay if you borrowed for a year at that rate. So one month gets multiplied and compounded 12 times, whereas 3 month loans don't have to be multiplied and compounded as often.|
        | What are the benefits of 3 month loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |            
        | Three month loans can be useful for some people, especially if they want a little longer to repay than a single month. Even if the amount you repay is the same as a payday loan overall, the ability to repay it in three instalments rather than in a one-off payment can make life easier in the short term.                                                                                                                                                                                                                                                                  |
        | Some people also don't want credit over a longer period of time. They'd rather just have a loan for as short an amount of time as possible, so a three month loan can be a good middle-point between a payday loan and a longer-term loan.                                                                                                                                                                                                                                                                                                                                       |   
        | What are the negatives of taking out 3 month loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |      
        | The main negatives of three month loans are similar to the negatives of payday loans. Even for a small loan, repaying the entire amount in a small amount of time means each regular repayment amount would be higher than if you paid it back over a longer term. This could be difficult to budget for, especially if you've needed money over the short term enough that you needed the loan in the first place.                                                                                                                                                              |
        | There's also a potential issue with some other lenders. If the loan is classified as a payday loan, some mortgage providers may take this as a sign of poor financial management. In some cases, some have even said it could be taken as a factor with regards to approving someone for a larger loan or mortgage. This has been a controversial stance, and it's one that most mortgage providers don't take into account, but there are a small number who do.                                                                                                                |
        | What alternatives are there to 3 month loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
        | There are plenty of alternatives to three month loans, depending on your ability to repay. Some lenders offer loans for a longer period of time (like Lending Stream), meaning that you have lower monthly repayments.                                                                                                                                                                                                                                                                                                                                                           |
        | There are also more traditional payday loans. These are usually for a few weeks or around a month, and you repay the amount you borrow (plus interest) on your next payday.                                                                                                                                                                                                                                                                                                                                                                                                      |
        | You may qualify for a line of credit - this is like an overdraft in some ways. Basically, you are given access to an amount of money, which you can repay and reuse as often as you like. You only pay interest on the money you borrow while you borrow it, so if you don't use it, it doesn't cost you anything. Lending Stream doesn't offer a line of credit, but our sister site, Drafty, does.                                                                                                                                                                             |
        | Related Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
        | Bad Credit Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
        | Payday Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
        | Short-term Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
        | Compare Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
        | Quick Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
        | Unsecured Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
        | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                                                                                                                                                                            |

@LS @Loans_Page @3_Month_Loans @UI @Desktop @MobileView @Body @link 
Scenario:LS:Loans: Check all the link in 3_Month_Loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/3-month-loans/"
    Then user verifies '3_month_loans' URL
    Then verify the links in '3_month_loans' page
        | link                      | URL                                                                         |
        | Home                      | https://preprod2-re.globalanalytics.in/                                     |
        | Loans                     | https://preprod2-re.globalanalytics.in/loans/                               |
        | 3 Month Loans             | https://preprod2-re.globalanalytics.in/loans/3-month-loans/                 |
        | Apply Now                 | https://preprod2-re.globalanalytics.in/application/apply/                   |
        | moneyadviceservice.org.uk | https://www.moneyadviceservice.org.uk/en                                    |
        | Payday loans              | https://preprod2-re.globalanalytics.in/loans/payday-loans/                  |
        | payday loans              | https://preprod2-re.globalanalytics.in/loans/payday-loans/                  |
        | Drafty                    | https://www.drafty.co.uk/                                                   |
        | Bad Credit Loans          | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/              |
        | Payday Loans              | https://preprod2-re.globalanalytics.in/loans/payday-loans/                  |
        | Short-term Loans          | https://preprod2-re.globalanalytics.in/loans/short-term-loans/              |
        | Compare Loans             | https://preprod2-re.globalanalytics.in/compare-loans/short-term-loans-compare/ |
        | Quick Loans               | https://preprod2-re.globalanalytics.in/loans/quick-loans/                   |
        | Unsecured Loans           | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/               |
