Feature: Lending stream Loans Bad credit loans page test plan

@LS @Desktop @MobileView @UI @Loans_Page @bad-credit-loans @Body @content 
Scenario:LS: loans : Verify the body content in bad-credit-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/"
    Then user verifies the 'bad-credit-loans' url 
    Then verify the content of the 'bad-credot-loans' page
     | content                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | Lending Stream Loans for Bad Credit                                                                                                                                                                                                                                                                                                                                                                                               |
     | How to find bad credit loans and stay safe.                                                                                                                                                                                                                                                                                                                                                                                       |
     | Loans For Bad Credit                                                                                                                                                                                                                                                                                                                                                                                                              |
     | Even if it can feel like nobody is willing to lend to you because of your credit history, it still might be possible to get a loan for bad credit. These are also sometimes referred to as ‘emergency loans’ and may take the form of loans like payday loans or other short-term loans.                                                                                                                                          |
     | Most lenders who offer loans for bad credit will still need to take your credit score into account, but it won’t be the only factor they look at. Here at Lending Stream, we understand that your current finances might be different to your past behaviour. So we’ll take a close look at your current finances to help us figure out if you can afford a loan, even with bad credit.                                           |
     | It’s important to look around and make sure you’re getting a loan that’s right for you, no matter how good or bad your credit history.                                                                                                                                                                                                                                                                                            |
     | Lending Stream Bad Credit Loans                                                                                                                                                                                                                                                                                                                                                                                                   |
     | If you apply with Lending Stream, we’ll give you a near-instant decision based on your finances. This doesn’t just mean looking at your credit record – we’ll also look at your current income and outgoings to help us decide.                                                                                                                                                                                                   |
     | You might expect to have to send in paperwork, while we make a decision (especially with loans for bad credit). But because we use open banking, we don’t need you to do that. Open banking is a secure way for you to give us information about your finances, while keeping your private information safe. And it’s seriously fast – we’ll give you a decision quickly.                                                         |
     | If we offer you a loan, it'll be because we believe you can repay, based on our checks and the information that you provide. Even if you have bad credit.                                                                                                                                                                                                                                                                         |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                     |
     | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                        |
     | Does bad credit stop me getting any loans?                                                                                                                                                                                                                                                                                                                                                                                        |
     | Having bad credit won’t prevent you from applying for any loan but getting approved may be difficult. Generally speaking, direct lenders might offer better rates to people with better credit ratings. Basically, having a good or bad credit rating is a measure of how good you've been at repaying credit. Having poor credit suggests you're a higher risk, so the price of the loan reflects that.                          |
     | This is why ‘loans for bad credit’ like payday loans or other forms of high-cost short-term credit exist. They’re much shorter term, unsecured loans which people with bad credit might be more likely to be accepted for. They’re also generally for smaller amounts than some other loan providers might offer. But there’s far less risk involved for the lender than loans like credit cards or mortgages.                    |
     | Also, lenders concentrating on small loans for bad credit may be less concerned with a poor credit rating. As long as you can show that you can afford the loan repayments after taking into account your income and outgoings, then they may still lend to you. So this means that there might be loans available for people with bad credit.                                                                                    |
     | Payday loans for bad credit                                                                                                                                                                                                                                                                                                                                                                                                       |
     | Payday loans are often thought of as ‘loans for bad credit’. This is because high-cost short term credit is often perceived as being something of a last resort. After all, if someone has access to cheaper credit, they’ll likely use that instead.                                                                                                                                                                             |
     | Traditional payday loans were often for around a month, with the entire loan amount being paid back along with the interest in one go. These are still around, but aren’t as popular as they once were.                                                                                                                                                                                                                           |
     | Most lenders that offered payday loans for bad credit are more likely to offer short-term loans for 3, 6 or 12 months. At Lending Stream, we’ve offered 6 month loans for a long time. We think that if you need the cash now, you’ll probably need a bit longer than one month to pay it back.                                                                                                                                   |
     | However, if you’d still prefer to repay in a month, you can! With Lending Stream, you can repay as much as you like, as early as you like. You’ll even save cash by doing so.                                                                                                                                                                                                                                                     |
     | Loans for bad credit no guarantor                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Some lenders might be more willing to lend to you if you have a guarantor. This means someone else is willing to make repayments for your loan if you can’t. In some cases, the loan will actually be sent to the guarantor, and they then transfer it to you. You then make the repayments.                                                                                                                                      |
     | These can be useful as a way to build some good credit history if you have a friend that is willing to help you out. However, they can be embarrassing to ask for help with, and you are in danger of causing problems for your friend if you don’t repay.                                                                                                                                                                        |
     | At Lending Stream, we don’t ask for a guarantor if you apply for a loan. We’d prefer to deal with you directly.                                                                                                                                                                                                                                                                                                                   |
     | Unsecured loans for bad credit                                                                                                                                                                                                                                                                                                                                                                                                    |
     | The difference between secured loans and unsecured loans is that you put something up as collateral for a secured loan. This means that whatever you put up becomes the property of the lender if you don’t repay. Examples of these might include pawn shops, log books loans or loans based on mortgages.                                                                                                                       |
     | With unsecured loans, you don’t need to do this. However, this might mean that the loan is more expensive, because the lender is taking more of a risk. This is why lenders might want to see more financial information before they agree to offer a loan. It’s also why we use Open Banking to help us make lending decisions based on your current finances. It also lets us do it while keeping your data safe.               |
     | How do I know if I have bad credit?                                                                                                                                                                                                                                                                                                                                                                                               |
     | Finding out your credit rating has never been easier. There are three credit reference agencies in the UK – CallCredit, Experian and Equifax. You can view your credit report either through them or through sites like Clearscore or Noddle, who show you your information in a user-friendly way.                                                                                                                               |
     | One thing, just in case you're worried – viewing your credit score isn't the same thing as a credit search. When you apply for credit, the potential lender can search your credit file to make their decision. This can (slightly) reduce your credit score, especially if you apply for credit multiple times in a short time period. But you can view your own credit record as often as you want without causing any issues.  |
     | Credit reference agencies keep track of your credit history, including the amount of credit you have and how you're doing on repayments. They also show where and who your financial history is linked to, which is useful if there are any possibilities of identity theft. When lenders search your credit file, they don't just see the 'score' you're given – they see your credit file and data for the last several years.  |
     | They also show bad debts that have been reported to credit agencies – for example, unpaid utility bills. These can cause major problems on your credit score, so if they turn out to be mistakes or relatively easily resolved, this is worth knowing about. With bad debts like these, you may be able to resolve them and request them to remove the bad credit mark.                                                           |
     | What problems can bad credit cause me?                                                                                                                                                                                                                                                                                                                                                                                            |
     | Bad credit can cause you problems if you need to borrow in future. This may not be an issue immediately, but it could be a problem if you look for a mortgage, overdraft, credit card, etc.                                                                                                                                                                                                                                       |
     | It also could lead to the amount of credit available to you being reduced. In a situation like this, your credit card balance or overdraft limit could be reduced.                                                                                                                                                                                                                                                                |
     | How can I improve my credit rating?                                                                                                                                                                                                                                                                                                                                                                                               |
     | While this does not constitute financial advice, there are some straightforward steps (and some less straightforward ones) that may be able to help you improve your credit rating.                                                                                                                                                                                                                                               |
     | 1. Pay back whatever debt you can afford. One of the main things your credit score shows is how much of your available credit you're using. If you can lower that, that will almost certainly help your rating improve.                                                                                                                                                                                                           |
     | 2. Check for mistakes and outdated information. Are you still shown as living at an old address? Are you still financially linked to an ex-partner? There may be issues with your credit report that you know nothing about until you look – and some of them could be easily resolved.                                                                                                                                           |
     | 3. Make sure you repay on due dates. Using less credit will be useful, but if you constantly repay late, this will be a problem as well.                                                                                                                                                                                                                                                                                          |
     | If these three issues are all currently negatives on your credit report, then these will be useful first steps. However, there are more steps you can take if necessary. For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                               |
     | Related Loans                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                             |

@LS @Desktop @MobileView @UI @Loans_Page @bad-credit-loans @Body @content @table 
Scenario: LS: loans : Verify the table data in bad-credit-loans page
     Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/"
     Then user verifies the 'bad-credit-loans' url
     Then verify 'Representative example' heading is present
     Then verify content of Representative example table
      | left_value             | right_value |
      | Annual Interest Rate   | 292.0%      |
      | Total amount of credit | £200        |
      | Representative APR     | 1333%       |
      | Duration of agreement  | 6 months    |
      | Total amount payable   | £386.61     |
      | Total charge of credit | £186.61     |
      | Six repayments of:     | £64.44      |

@LS @Desktop @MobileView @UI @Loans_Page @bad-credit-loans @Body @link 
Scenario:LS: loans : Check all the links in bad-credit-loans page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/"
    Then user verifies the 'bad-credit-loans' url
    Then verify the links in 'bad-credit-loans' page
     | link                      | url                                                                            |
     | Home                      | https://preprod2-re.globalanalytics.in/                                        |
     | Loans                     | https://preprod2-re.globalanalytics.in/loans/                                  |
     | Bad Credit Loans          | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/                 |
     | Apply Now                 | https://preprod2-re.globalanalytics.in/application/apply/                      |
     | moneyadviceservice.org.uk | https://www.moneyadviceservice.org.uk/en                                       |
     | moneyadviceservice.org.uk | https://www.moneyadviceservice.org.uk/en                                       |
     | Short-Term Loans          | https://preprod2-re.globalanalytics.in/loans/short-term-loans/                 |
     | Payday Loans              | https://preprod2-re.globalanalytics.in/loans/payday-loans/                     |
     | Unsecured Loans           | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/                  |
     | Compare Loans             | https://preprod2-re.globalanalytics.in/compare-loans/short-term-loans-compare/ |
     | Quick Loans               | https://preprod2-re.globalanalytics.in/loans/quick-loans/                      |
     | Same Day Loans            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/                   |
