Feature:Verify the faq complaints

@LS @UI @MobileView @Desktop @Body @content @Faqs @complaints 
 Scenario:LS: FAQ: complaint : Verify the body content of register a complaint
    Given I open direct url as "https://preprod2-re.globalanalytics.in/faqs/complaints"
    Then user verifies 'complaints' URL
    Then verify the content of 'complaints' page
    | Content                                                                                                                                                                                                                                                                                                                             |
    | How can I register a complaint?                                                                                                                                                                                                                                                                                                     |
    | Your satisfaction is important to us. If you have a concern about our service or performance, we want to hear about it straight away.                                                                                                                                                                                               |
    | You can file a complaint:                                                                                                                                                                                                                                                                                                           |
    | on our Contact Us page                                                                                                                                                                                                                                                                                                              |
    | you can also contact us via chat by logging in to your account section                                                                                                                                                                                                                                                              |
    | We strive to resolve complaints as quickly as possible. We'll acknowledge your complaint within two business days of receiving it. It is always our goal to resolve the issue for you as quickly as possible.                                                                                                                       |
    | We'll respond in writing within 14 days of the original complaint with:                                                                                                                                                                                                                                                             |
    | our understanding of the situation at hand                                                                                                                                                                                                                                                                                          |
    | a proposal to resolve the issue                                                                                                                                                                                                                                                                                                     |
    | options available to you if you're not satisfied with our initial response.                                                                                                                                                                                                                                                         |
    | If we cannot resolve it within eight weeks, we will:                                                                                                                                                                                                                                                                                |
    | tell you why we're having trouble resolving it                                                                                                                                                                                                                                                                                      |
    | keep you updated on the status of your complaint                                                                                                                                                                                                                                                                                    |
    | let you know when to expect to hear from us again.                                                                                                                                                                                                                                                                                  |
    | If you've gone through our entire complaints process and you're still not satisfied with our final response or have not received a final response from us within 8 weeks of making your complaint, the Financial Ombudsman Service may be able to help - visit www.financial-ombudsman.org.uk or phone 0300 123 9123 (call charges apply) or 0800 023 4567 (free from most phone networks). |
    | You may also submit a complaint to the European Commission Online Dispute Resolution portal.                                                                                                                                                                                                                                        |                
    | Download our full complaints handling procedure here.                                                                                                                                                                                                                                                                               |
    | Back to FAQs                                                                                                                                                                                                                                                                                                                        |
    | Representative 1333% APR                                                                                                                                                                                                                                                                                                            |
    | Learn more about the cost of your loan, default charges, risks and prepayments. |
    | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short-term financial needs but which is not appropriate for longer-term borrowing or if you are in financial difficulty. All loan applications are subject to status checks, terms and conditions, and to satisfactory passage of checks on creditworthiness and affordability. |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.|

 @LS @UI @MobileView @Desktop @Body @Complaints @link @Faqs @complaints 
    Scenario:LS: FAQ: complaint : Verify all the links in register a complaint body
        Given I open direct url as "https://preprod2-re.globalanalytics.in/faqs/complaints"
        Then user verifies 'complaints' URL
        Then verify the links in 'complaints' page
    | Link                                                 | URL                                                                                  |    
    | Home                                                 | https://preprod2-re.globalanalytics.in/                                              |
    | Faqs                                                 | https://preprod2-re.globalanalytics.in/faqs/                                         |
    | Complaints                                           | https://preprod2-re.globalanalytics.in/faqs/complaints                               |
    | Contact Us                                           | https://preprod2-re.globalanalytics.in/contactus/                                    |
    | Back to FAQs                                         | https://preprod2-re.globalanalytics.in/faqs/                                         |
    | cost of your loan                                    | https://preprod2-re.globalanalytics.in/faqs/representative-example/                  |
    | default charges                                      | https://preprod2-re.globalanalytics.in/faqs/loan-fees/                               |
    | risks and prepayments                                | https://preprod2-re.globalanalytics.in/faqs/loan-risks/                              |
   
@LS @UI @MobileView @Desktop @Body @Complaints @link @Faqs @complaints
    Scenario:LS: FAQ: complaint : Verify the different portal links in register a complaint
        Given I open direct url as "https://preprod2-re.globalanalytics.in/faqs/complaints"
        Then user verifies 'complaints' URL
        Then verify the different site links on 'complaints' page
        | Link                                                 | URL                                                                                 |    
        | www.financial-ombudsman.org.uk                       | https://www.financial-ombudsman.org.uk/                                             |
        | European Commission Online Dispute Resolution portal | https://ec.europa.eu/consumers/odr/main/index.cfm?event=main.home2.show&lng=EN.     | 
        | Download our full complaints handling procedure      | https://d6b2d27m4ech5.cloudfront.net/resources/Complaints_handling_procedure_v2.pdf | 
