Feature: Verification on Lendingstream home page body section

@LS @Desktop @MobileView @UI @home @Body @content @Automation 
Scenario: LS: home page: Verify the body content in the Home page
    Given I open direct url as "https://preprod2-re.globalanalytics.in/"
    Then user verifies 'homepage' URL   
    Then verify the content of 'homepage'
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | During the Coronavirus situation, we want to keep you updated on any impact it's having to our services and how to get help if you need it. Read our latest update.                                                                                                                                                                                                                                                                                                         |
     | Welcome to loan streaming                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | Apply for up to £1,500 with 6 months to repay                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                               |
     | For help go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | Lending Stream - your alternative to payday loans                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | Need a payday loan?                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | How about 6 months to repay, instead of paying it all back in one go? You may find it's easier on your budget than a payday loan and you'll get the cash as fast as most payday lenders manage.                                                                                                                                                                                                                                                                             |
     | Money streamed to your bank in under 90 seconds.                                                                                                                                                                                                                                                                                                                                                                                                                            |
     | If you're applying for a short-term loan with us, we know you need cash fast. That's why, in most cases, once agreed, we can send cash to your bank within 90 seconds.                                                                                                                                                                                                                                                                                                      |
     | Bad credit holding you back?                                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Having short term financial problems doesn't always mean you're bad with finances. We understand this. So we'll look at more than just your credit history when considering your ability to repay.                                                                                                                                                                                                                                                                          |
     | Ready to start streaming?                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Learn more about the cost of your loan, default charges, risks and prepayments.                                                                                                                                                                                                                                                                                                                                                                                             |
     | Responsible Lending: Carefully consider whether a loan is right for your individual financial situation. Borrowing of this type is an expensive form of credit that may be appropriate for short-term financial needs but which is not appropriate for longer-term borrowing or if you are in financial difficulty. All loan applications are subject to status checks, terms and conditions, and to satisfactory passage of checks on credit-worthiness and affordability. |
     | Better than payday loans?                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
     | Lending Stream loans are a six-month alternative to "payday loans". They're fast (we'll send the money to your bank in under 90 seconds)  with spread out monthly repayments. Want to pay off early? That's fine - there's no charge and you'll pay less interest!                                                                                                                                                                                                          |
     | Streaming loans for bad credit?                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | You might be able to repay a loan but have bad credit because of recent difficulties. We understand that this can happen sometimes, so when we look at your application, we look at all your information to make sure it's affordable, not just your credit history. Because you're more than just a number.                                                                                                                                                                |
     | Don't just take our word for it...                                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Have you checked out our reviews? There are a lot of four and five star ratings in there. That's because we focus on customers like you, so we developed a smooth, responsive application process and concentrate on customer service.                                                                                                                                                                                                                                      |
     | The Stream blog                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | Got a few minutes spare? Check out our blog, where we publish customer research, money saving tips and features that you might find interesting.                                                                                                                                                                                                                                                                                                                            |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees.                                                                                                                       |

@LS @Desktop @MobileView @UI @home @Body @slide @Automation 
Scenario: LS: home page: Check the Customer Reviews in Home page  
    Given I open direct url as "https://preprod2-re.globalanalytics.in/"
    Then user verifies 'homepage' URL  
    Then verify 'Read Our Reviews' is dispalyed 
    Then verify  content of slides
     |Slides Content                                                                                             |
     |"I love this company. They have always been there when I have needed them. Would highly recommend them"    |
     |Tania, 14th January 2020                                                                                   |
     |"I would recommend lending stream to friends and family.Thank you."                                        |
     |keely, 16th January 2020                                                                                   |                                 
     |"Thanks Lending Stream for helping me. Quick and easy application process."                                |
     |Gavin, 20th January 2020                                                                                   |
 
@LS @Desktop @MobileView @UI @home @Body @link @Automation
Scenario: LS: home page: Check all the links in the Home page body
    Given I open direct url as "https://preprod2-re.globalanalytics.in/"
    Then user verifies 'homepage' URL
    Then verify the links in 'homepage' page
     | Link                       | URL                                                                 |
     | latest update              | https://preprod2-re.globalanalytics.in/COVID19support/              |
     | Apply Now                  | https://preprod2-re.globalanalytics.in/application/apply/           |
     | moneyadviceservice.org.uk  | https://www.moneyadviceservice.org.uk/en                            |
     | Read more reviews          | https://lending-stream.reviews.co.uk/                               |
     | Apply Now                  | https://preprod2-re.globalanalytics.in/application/apply            |
     | cost of your loan          | https://preprod2-re.globalanalytics.in/faqs/representative-example/ |
     | default charges            | https://preprod2-re.globalanalytics.in/faqs/loan-fees/              |
     | risks and prepayments      | https://preprod2-re.globalanalytics.in/faqs/loan-risks/             |
     | payday loans               | https://preprod2-re.globalanalytics.in/loans/payday-loans/          |
     | our blog                   | https://preprod2-re.globalanalytics.in/blog/                        |   

