Feature: verify content in loans-Quick Payday Loans

@LS @Loans_Page @quick-loans @UI @Desktop @MobileView @Body @content 
Scenario:LS: Loans: Verify the body content in Quick Payday Loans
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/quick-loans/"
    Then user verifies the 'quick-loans' url 
    Then verify the content of 'quick-loans' page
     | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | Quick Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
     | How to apply for quick loans                                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | What kind of quick loans are there?                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | If you need a quick loan, there are plenty of options online. These include payday loans, instalment loans and secured loans.                                                                                                                                                                                                                                                                                                                                            |
     | Payday loans are short-term loans (usually for a few hundred pounds) that are repaid on your next payday(s).                                                                                                                                                                                                                                                                                                                                                             |
     | Instalment loans are usually for a bit more money and repaid over a number of months. This is what Lending Stream offers – we believe it's more affordable than a payday loan.                                                                                                                                                                                                                                                                                           |
     | Secured loans are lent against something that you own, unlike instalment or payday loans. This could be your personal belongings (like with a pawn shop), your car (like with a log book loan) or even your home (although these are usually for a larger amount and a longer period of time).                                                                                                                                                                           |
     | Some places also offer 'guarantor loans', which are similar to instalment loans, but you need to have a guarantor. This guarantor must have good credit, as the agreement is that they will take over the repayments if you do not pay on time.                                                                                                                                                                                                                          |
     | Lending Stream Quick Loans                                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | If you're in need of some quick cash, then take a look at Lending Stream quick loans. We offer loans that you repay over six months, spreading the amount of the loan out so you're not repaying the entire amount off in one go.                                                                                                                                                                                                                                        |
     | Find out more about our quick loans here:                                                                                                                                                                                                                                                                                                                                                                                                                                |
     | Representative 1333% APR                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
     | Warning: Late repayment can cause you serious money problems.                                                                                                                                                                                                                                                                                                                                                                                                            |
     | For help, go to moneyadviceservice.org.uk.                                                                                                                                                                                                                                                                                                                                                                                                                               |
     | How do I apply for quick loans?                                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Usually, you can apply online for quick loans.                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | Most lenders will need you to provide them with your address, bank details and information about your income and outgoings. This is so they can verify that you can afford the loan and arrange automatic repayments. In some rare cases, they may contact your employer to verify you work there (although will not disclose the reason for contacting them) or you may also need to provide them with three months of bank statements before they can make a decision. |
     | Some lenders have a high street store, so you can also apply in person. There's no real difference in applying either way, unless you have to provide documents to support your application – in which case, you can do it in person rather than scanning and emailing them.                                                                                                                                                                                             |
     | Are quick loans safe?                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Check to see if the lender has been licensed and authorised by the FCA (Financial Conduct Authority). If they are, then they're reputable lenders and they have to abide by the same laws as other lenders.                                                                                                                                                                                                                                                              |
     | That said, it's important to be realistic about whether you can repay the loan amount. If you're getting into a pattern of taking out short-term credit, it can become financially difficult. Quick loans aren't usually designed for ongoing use.                                                                                                                                                                                                                       |
     | Are there quick loans without fees?                                                                                                                                                                                                                                                                                                                                                                                                                                      |
     | Some lenders don't charge any fees. You shouldn't have to pay a fee to apply – if you do, be very careful and do check if they're properly licenced.                                                                                                                                                                                                                                                                                                                     |
     | You'll almost certainly have to pay interest, though. And if it's short-term, then that interest is likely to be higher than a longer-term loan.                                                                                                                                                                                                                                                                                                                         |
     | Can you get quick loans without a guarantor?                                                                                                                                                                                                                                                                                                                                                                                                                             |
     | If the lender believes you can repay, then you shouldn't need a guarantor. If you have particularly bad credit, or if the lender has reason to believe you are unlikely to repay, you may struggle to get a loan without one.                                                                                                                                                                                                                                            |
     | Can you get quick loans without a credit check?                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Reputable lenders will usually check your credit file. Some brokers may claim not to, but that's because they'll almost always pass your details on to lenders who then do so.                                                                                                                                                                                                                                                                                           |
     | Be careful when applying. If someone is offering 'no credit check payday loans' or similar, they probably don't have your best interests at heart.                                                                                                                                                                                                                                                                                                                       |
     | That said, credit checks aren't usually the only thing that lenders look at. If you have enough income to cover your outgoings and the extra incurred by the quick loan, they may still be able to lend to you even if you have a poor credit history.                                                                                                                                                                                                                   |
     | Do quick loans have a high APR?                                                                                                                                                                                                                                                                                                                                                                                                                                          |
     | Yes, they usually do. If you take out a loan for a short amount of time, the APR will usually be high. This is partly because APR stands for Annual Percentage Rate, so the shorter the loan period, the more times it has to be multiplied and compounded to show what you'd pay over a year at the same rates.                                                                                                                                                         |
     | If you want to judge the cost and affordability of a loan, it's worth looking at how much you'd repay and over what time period.                                                                                                                                                                                                                                                                                                                                         |
     | Quick loans and debt                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
     | If you find you're taking quick loans on a regular basis, it could be a sign that you're getting in more debt that you can handle. It's important to be aware of your income and outgoings and take a longer-term view, to make sure you're not getting into a debt spiral.                                                                                                                                                                                              |
     | Quick loans are designed to be used occasionally at most. If you're using them regularly, you may be experiencing more financial difficulty than you realise.                                                                                                                                                                                                                                                                                                            |
     | If you're having difficulty repaying your loans, then you should contact your lender immediately. They may be able to arrange a repayment plan to help you pay off without incurring further interest.                                                                                                                                                                                                                                                                   |
     | How to be careful when I apply for quick loans                                                                                                                                                                                                                                                                                                                                                                                                                           |
     | Follow these three simple steps and that should help.                                                                                                                                                                                                                                                                                                                                                                                                                    |
     | Make sure you're dealing with a reputable lender                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | Check the amount and loan period                                                                                                                                                                                                                                                                                                                                                                                                                                         |
     | Make sure you can afford the repayments                                                                                                                                                                                                                                                                                                                                                                                                                                  |
     | Related Loans                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
     | We don't offer loans under 60 days. Early prepayment options that are available are not associated with any fees or cost. Maximum APR 1721%. Given a Representative APR is 1333%, if you borrow £200 over 6 months at 292.0% p.a. (fixed), you would owe 6 equal repayments of £64.44. You will repay £386.61 in total. There are no additional fees. |

@LS @Loans_Page @quick-loans @UI @Desktop @MobileView @Body @link 
Scenario:LS: Loans: Verify the links in Quick Payday Loans
    Given I open direct url as "https://preprod2-re.globalanalytics.in/loans/quick-loans/"
    Then user verifies the 'quick-loans' url 
    Then verify the links and URLs of 'quick-loans' page   
     | link                      | url                                                                            |
     | Home                      | https://preprod2-re.globalanalytics.in/                                        |
     | Loans                     | https://preprod2-re.globalanalytics.in/loans/                                  |
     | Quick Payday Loans        | https://preprod2-re.globalanalytics.in/loans/quick-loans/                      |
     | Payday loans              | https://preprod2-re.globalanalytics.in/loans/payday-loans/                     |
     | Apply Now                 | https://preprod2-re.globalanalytics.in/application/apply/                      |
     | moneyadviceservice.org.uk | https://www.moneyadviceservice.org.uk/en                                       |
     | Bad Credit Loans          | https://preprod2-re.globalanalytics.in/loans/bad-credit-loans/                 |
     | Payday Loans              | https://preprod2-re.globalanalytics.in/loans/payday-loans/                     |
     | Short-Term Loans          | https://preprod2-re.globalanalytics.in/loans/short-term-loans/                 |
     | Compare Loans             | https://preprod2-re.globalanalytics.in/compare-loans/short-term-loans-compare/ |
     | Same Day Loans            | https://preprod2-re.globalanalytics.in/loans/same-day-loans/                   |
     | Unsecured Loans           | https://preprod2-re.globalanalytics.in/loans/unsecured-loans/                  |
